var _yt_www={};(function(m){var window=this;var pa;var oa;m.aa=function(a){return function(){return m.ba[a].apply(this,arguments)}};m.ca=function(a){return void 0!==a};m.l=function(a,b,c){a=a.split(".");c=c||m.p;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&(0,m.ca)(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};m.q=function(a,b){for(var c=a.split("."),d=b||m.p,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};m.ea=function(){};
m.fa=function(a){a.getInstance=function(){return a.Oa?a.Oa:a.Oa=new a}};
m.ha=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};m.ia=function(a){return"array"==(0,m.ha)(a)};m.ja=function(a){var b=(0,m.ha)(a);return"array"==b||"object"==b&&"number"==typeof a.length};m.r=function(a){return"string"==typeof a};m.ka=function(a){return"number"==typeof a};m.la=function(a){return"function"==(0,m.ha)(a)};m.ma=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};m.na=function(a){return a[oa]||(a[oa]=++pa)};
var qa=function(a,b,c){return a.call.apply(a.bind,arguments)};var ra=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};m.s=function(a,b,c){m.s=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?qa:ra;return m.s.apply(null,arguments)};
m.t=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};m.v=function(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Iv=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};m.sa=function(a){m.sa[" "](a);return a};
m.ta=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,m.ta);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};m.ua=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};m.va=function(a){return(0,window.encodeURIComponent)(String(a))};
m.wa=function(a){if(!xa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ya,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(za,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Aa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ba,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ca,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Da,"&#0;"));return a};m.Ea=function(a,b){return-1!=a.indexOf(b)};
m.Ga=function(a,b){for(var c=0,d=(0,m.ua)(String(a)).split("."),e=(0,m.ua)(String(b)).split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var k=d[h]||"",n=e[h]||"",u=RegExp("(\\d*)(\\D*)","g"),E=RegExp("(\\d*)(\\D*)","g");do{var Q=u.exec(k)||["","",""],ga=E.exec(n)||["","",""];if(0==Q[0].length&&0==ga[0].length)break;c=Ha(0==Q[1].length?0:(0,window.parseInt)(Q[1],10),0==ga[1].length?0:(0,window.parseInt)(ga[1],10))||Ha(0==Q[2].length,0==ga[2].length)||Ha(Q[2],ga[2])}while(0==c)}return c};
var Ha=function(a,b){return a<b?-1:a>b?1:0};m.Ia=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};m.Ja=function(a){var b=(0,m.r)(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};m.Ka=function(a,b,c){b=(0,m.La)(a,b,c);return 0>b?null:(0,m.r)(a)?a.charAt(b):a[b]};
m.La=function(a,b,c){for(var d=a.length,e=(0,m.r)(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};m.Ma=function(a,b){return 0<=(0,m.Na)(a,b)};m.Oa=function(a,b){var c=(0,m.Na)(a,b),d;(d=0<=c)&&(0,m.Pa)(a,c);return d};m.Pa=function(a,b){m.Qa.splice.call(a,b,1)};m.Ra=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};m.Sa=function(a,b,c){return 2>=arguments.length?m.Qa.slice.call(a,b):m.Qa.slice.call(a,b,c)};m.Ta=function(){};
m.Ua=function(a,b){(0,m.Va)(a,(0,m.t)(m.Wa,b))};m.Va=function(a,b){a.za||(a.za=[]);a.za.push((0,m.ca)(void 0)?(0,m.s)(b,void 0):b)};m.Wa=function(a){a&&"function"==typeof a.dispose&&a.dispose()};m.Xa=function(){this.b=[];this.kb={}};m.Ya=function(a){Za(m.$a,arguments)};m.w=function(a,b){return a in m.$a?m.$a[a]:b};m.x=function(a,b){(0,m.la)(a)&&(a=(0,m.ab)(a));return window.setTimeout(a,b)};m.bb=function(a,b){(0,m.la)(a)&&(a=(0,m.ab)(a));return window.setInterval(a,b)};m.y=function(a){window.clearTimeout(a)};
m.cb=function(a){window.clearInterval(a)};m.ab=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw(0,m.db)(b),b;}}:a};m.db=function(a,b){if(window&&window.yterr){var c=(0,m.q)("yt.www.errors.log");c?c(a,b):(c=(0,m.w)("ERRORS")||[],c.push([a,b]),(0,m.Ya)("ERRORS",c))}};m.eb=function(a){Za(m.fb,arguments)};m.gb=function(a){return a in m.fb};
m.hb=function(a,b,c){var d=b||{};if(a=a in m.fb?m.fb[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});return a};var Za=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};m.z=function(a,b,c){var d=ib();if(d){var e=d.subscribe(a,function(){if(!m.jb||m.jb!=e){var d=arguments,h=function(){kb[e]&&b.apply(c||window,d)};try{lb[a]?h():(0,m.x)(h,0)}catch(k){(0,m.db)(k)}}},c);kb[e]=!0;mb[a]||(mb[a]=[]);mb[a].push(e);return e}return 0};
m.nb=function(a){var b=ib();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,m.A)(a,function(a){b.unsubscribeByKey(a);delete kb[a]}))};m.B=function(a,b){var c=ib();return c?c.publish.apply(c,arguments):!1};m.ob=function(a,b){lb[a]=!0;var c=ib(),c=c?c.publish.apply(c,arguments):!1;lb[a]=!1;return c};var ib=function(){return(0,m.q)("yt.pubsub.instance_")};m.pb=function(a){if(a.classList)return a.classList;a=a.className;return(0,m.r)(a)&&a.match(/\S+/g)||[]};
m.C=function(a,b){return a.classList?a.classList.contains(b):(0,m.Ma)((0,m.pb)(a),b)};m.D=function(a,b){a.classList?a.classList.add(b):(0,m.C)(a,b)||(a.className+=0<a.className.length?" "+b:b)};m.qb=function(a,b){if(a.classList)(0,m.A)(b,function(b){(0,m.D)(a,b)});else{var c={};(0,m.A)((0,m.pb)(a),function(a){c[a]=!0});(0,m.A)(b,function(a){c[a]=!0});a.className="";for(var d in c)a.className+=0<a.className.length?" "+d:d}};
m.F=function(a,b){a.classList?a.classList.remove(b):(0,m.C)(a,b)&&(a.className=(0,m.rb)((0,m.pb)(a),function(a){return a!=b}).join(" "))};m.sb=function(a,b,c){c?(0,m.D)(a,b):(0,m.F)(a,b)};m.tb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};m.ub=function(a,b,c){return Math.min(Math.max(a,b),c)};m.vb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};m.wb=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};m.xb=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};
m.yb=function(a){var b={},c;for(c in a)b[c]=a[c];return b};m.zb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ab.length;f++)c=Ab[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Bb=function(a){var b=arguments.length;if(1==b&&(0,m.ia)(arguments[0]))return Bb.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};var Cb=function(){return m.p.navigator||null};
var Db=function(){var a=m.p.document;return a?a.documentMode:void 0};m.Eb=function(a){return Fb[a]||(Fb[a]=0<=(0,m.Ga)(Gb,a))};m.Hb=function(a){return m.G&&Ib>=a};m.H=function(a){return(0,m.r)(a)?window.document.getElementById(a):a};m.Jb=function(a){var b=window.document;return(0,m.r)(a)?b.getElementById(a):a};m.I=function(a,b){var c=b||window.document,d=null;c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=(0,m.Kb)("*",a,b)[0];return d||null};
m.Kb=function(a,b,c){var d=window.document;c=c||d;a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},e=0,f=0,h;h=c[f];f++)a==h.nodeName&&(d[e++]=h);d.length=e;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(f=e=0;h=c[f];f++)a=h.className,"function"==typeof a.split&&(0,m.Ma)(a.split(/\s+/),b)&&(d[e++]=h);d.length=e;return d}return c};
m.Lb=function(a,b){(0,m.vb)(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Mb?a.setAttribute(Mb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})};m.Nb=function(a,b,c){return(0,m.Ob)(window.document,arguments)};
m.Ob=function(a,b){var c=b[0],d=b[1];if(!Qb&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',(0,m.wa)(d.name),'"');if(d.type){c.push(' type="',(0,m.wa)(d.type),'"');var e={};(0,m.zb)(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&((0,m.r)(d)?c.className=d:(0,m.ia)(d)?c.className=d.join(" "):(0,m.Lb)(c,d));2<b.length&&(0,m.Rb)(a,c,b,2);return c};
m.Rb=function(a,b,c,d){function e(c){c&&b.appendChild((0,m.r)(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];!(0,m.ja)(f)||(0,m.ma)(f)&&0<f.nodeType?e(f):(0,m.A)(Sb(f)?(0,m.Ra)(f):f,e)}};m.Tb=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};m.Ub=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};var Vb=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
var Wb=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};m.Xb=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};var Sb=function(a){if(a&&"number"==typeof a.length){if((0,m.ma)(a))return"function"==typeof a.item||"string"==typeof a.item;if((0,m.la)(a))return"function"==typeof a.item}return!1};
m.Yb=function(a,b,c,d){c||(a=a.parentNode);c=null==d;for(var e=0;a&&(c||e<=d);){if(b(a))return a;a=a.parentNode;e++}return null};m.Zb=function(){};var $b=function(a){if(a instanceof m.Zb)return a;if("function"==typeof a.Ta)return a.Ta(!1);if((0,m.ja)(a)){var b=0,c=new m.Zb;c.next=function(){for(;;){if(b>=a.length)throw m.ac;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");};
m.bc=function(a,b,c){if((0,m.ja)(a))try{(0,m.A)(a,b,c)}catch(d){if(d!==m.ac)throw d;}else{a=$b(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(e){if(e!==m.ac)throw e;}}};m.cc=function(a){if((0,m.ja)(a))return(0,m.Ra)(a);a=$b(a);var b=[];(0,m.bc)(a,function(a){b.push(a)});return b};m.dc=function(a,b,c,d,e,f,h){var k="";a&&(k+=a+":");c&&(k+="//",b&&(k+=b+"@"),k+=c,d&&(k+=":"+d));e&&(k+=e);f&&(k+="?"+f);h&&(k+="#"+h);return k};
m.ec=function(a){if(fc){fc=!1;var b=m.p.location;if(b){var c=b.href;if(c&&(c=(0,m.gc)(c))&&c!=b.hostname)throw fc=!0,Error();}}return a.match(hc)};m.gc=function(a){return(a=(0,m.ec)(a)[3]||null)&&(0,window.decodeURIComponent)(a)};m.ic=function(a){a=(0,m.ec)(a);return(0,m.dc)(null,null,null,null,a[5],a[6],a[7])};m.jc=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
m.lc=function(a,b,c){if((0,m.ia)(b))for(var d=0;d<b.length;d++)(0,m.lc)(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",(0,m.va)(b))};var mc=function(a,b){for(var c in b)(0,m.lc)(c,b[c],a);return a};m.nc=function(a){a=mc([],a);a[0]="";return a.join("")};m.oc=function(a,b){return(0,m.jc)(mc([a],b))};m.pc=function(a,b,c){a&&(c?a&&(a=(0,m.Nb)("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),(0,m.Xb)(a).body.appendChild(a)):qc(a,b))};
var qc=function(a,b){var c=new window.Image,d=""+rc++;sc[d]=c;c.onload=c.onerror=function(){b&&sc[d]&&b();delete sc[d]};c.src=a;c=eval("null")};m.tc=function(a,b,c){uc(c)[a]=b||(0,m.J)();b||vc(a)};var wc=function(a,b,c){var d=xc(c).span;c=uc(c);"number"==typeof b?d[a]=b:b in c&&(d[a]=(0,m.J)()-c[b])};
var yc=function(a){var b=uc(a),c=xc(a).span,d=xc(a).info,e=(0,m.q)("yt.timing.reportbuilder_");if(e){if(e=e(b,c,d,a))zc(e),Ac(a),Bc();return window.NaN}var e={v:2,s:"youtube",action:(0,m.w)("TIMING_ACTION")},f=(0,m.w)("TIMING_INFO")||{},h;for(h in f)d[h]=f[h];h=d.srt;delete d.srt;var k;h||0===h||(k=Cc.timing||{},h=Math.max(0,k.responseStart-k.navigationStart),(0,window.isNaN)(h)&&d.pt&&(h=d.pt));if(h||0===h)d.srt=h;d.h5jse&&(f=window.location.protocol+(0,m.q)("ytplayer.config.assets.js"),(f=Cc.getEntriesByName?
Cc.getEntriesByName(f)[0]:null)?d.h5jse=Math.round(d.h5jse-f.responseEnd):delete d.h5jse);b.aft||(b.aft=b.pbr&&b.pbs>b.pbr?b.pbr:b.pbs?b.pbs:b.vr&&b.cl&&b.cl>b.vr?b.cl:b.vr?b.vr:b.ol);b.vr&&b.gv&&(c.vl=Math.round(b.vr-b.gv));f=b._start;if(!Dc){k||(k=Cc.timing||{});var n;t:if(n=k,n.msFirstPaint)n=Math.max(0,n.msFirstPaint);else{var u=window.chrome;if(u&&(u=u.loadTimes,(0,m.la)(u))){var u=u(),E=1E3*Math.min(u.requestTime||window.Infinity,u.startLoadTime||window.Infinity),E=window.Infinity===E?0:n.navigationStart-
E;n=Math.max(0,Math.round(1E3*u.firstPaintTime+E)||0);break t}n=0}0<n&&n>f&&(b.fpt=n);n=k.redirectEnd-k.redirectStart;0<n&&(c.rtime_=n);n=k.domainLookupEnd-k.domainLookupStart;0<n&&(c.dns_=n);n=k.connectEnd-k.connectStart;0<n&&(c.tcp_=n);n=k.connectEnd-k.secureConnectionStart;k.secureConnectionStart&&0<n&&(c.stcp_=n);n=k.responseStart-k.requestStart;0<n&&(c.req_=n);n=k.responseEnd-k.responseStart;0<n&&(c.rcv_=n);Dc=!0}.001>Math.random()&&Ec(c);for(var Q in d)"_"!=Q.charAt(0)&&(e[Q]=d[Q]);d={};Q=[];
for(var ga in b)"_"!=ga.charAt(0)&&(n=Math.max(Math.round(b[ga]-f),0),d[ga]=n,Q.push(ga+"."+n));e.rt=Q.join(",");b={};ga=[];for(var da in c)"_"!=da.charAt(0)&&(b[da]=c[da],ga.push(da+"."+c[da]));e.it=ga.join(",");zc(e);(c=(0,m.q)("ytdebug.logTiming"))&&c(e,d,b);Ac(a);Bc();return d.aft+(h||0)};
var Fc=function(a){var b=(0,m.w)("TIMING_ACTION"),c=uc();if(b&&c._start)if(b=(0,m.w)("TIMING_WAIT",[]),!a&&b.length){a=!0;for(var d=0,e=b.length;d<e;++d)if(!(b[d]in c)){a=!1;break}if(a)return yc()}else if(c.ol||c.aft)return yc();return window.NaN};var Gc=function(a){if((0,m.w)("TIMING_WAIT"))a=Fc();else t:{var b=(0,m.w)("TIMING_ACTION"),c=!!(0,m.w)("TIMING_WFF"),d=uc(a);if(b&&d._start){if(c&&d.vr||!c&&(d.ol||d.aft)){a=yc(a);break t}a&&yc(a)}a=window.NaN}return a};
var zc=function(a){var b="https:"==window.location.protocol?"https://gg.google.com/csi":"http://csi.gstatic.com/csi",c="",d;for(d in a)c+="&"+d+"="+a[d];(0,m.pc)(b+"?"+c.substring(1))};var uc=function(a){return xc(a).tick};var xc=function(a){return(0,m.q)("ytcsi."+(a||"")+"data_")||Ac(a)};var Ac=function(a){var b={tick:{},span:{},info:{}};(0,m.l)("ytcsi."+(a||"")+"data_",b,void 0);return b};m.Hc=function(){return!!(0,m.q)("yt.scheduler.instance")};
m.Ic=function(){return(0,m.Hc)()&&(0,m.C)(window.document.body,"exp-js-scheduler-more")};m.Jc=function(a,b){void 0===b&&(b=window.NaN);var c=(0,m.q)("yt.scheduler.instance.addJob");return c?((0,window.isNaN)(b)&&(b=0),c(a,0,b)):(0,window.isNaN)(b)?(a(),window.NaN):(0,m.x)(a,b||0)};m.Kc=function(a){var b=(0,m.q)("yt.scheduler.instance.cancelJob");b?b(a):(0,m.y)(a)};m.Lc=function(a){for(var b=0,c=a.length;b<c;b++)(0,m.Kc)(a[b])};
m.Mc=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.B=d?(0,m.ab)(d):null;this.A=e?(0,m.ab)(e):null;this.k=[];this.g=this.j=0};m.Nc=function(a){if((0,m.Ic)()){(0,m.Kc)(a.j);var b;b=(0,m.s)(a.init,a);b=(0,m.Jc)(b,void 0);a.j=b}else a.init()};m.Oc=function(a){a.name in Pc&&Qc(a.name);Pc[a.name]={reqs:[],disable:(0,m.s)(a.disable,a)};(0,m.A)(a.deps,function(b){if(!(b in Pc))throw Error("Module "+b+" required by "+a.name);Pc[b].reqs.push(a.name)});a.enable()};
var Qc=function(a){if(a in Pc){var b=Pc[a];(0,m.A)(b.reqs,function(a){Qc(a)});try{b.disable()}catch(c){}delete Pc[a]}};m.Rc=function(a){return a&&"readyState"in a?a.readyState:0};var Sc=function(){if((0,m.w)("SCHEDULE_AJAX")&&window.XMLHttpRequest&&!Tc){Uc=(0,m.w)("SCHEDULER_BUFFER_LENGTH");var a=window.XMLHttpRequest;Vc=a.prototype.abort;Wc=a.prototype.open;Tc=a.prototype.send;a.prototype.abort=Xc;a.prototype.open=Yc;a.prototype.send=Zc}};var Xc=function(){$c(!0);Vc.call(this)};
var Yc=function(){this.url=arguments[1];Wc.apply(this,arguments)};var Zc=function(){var a=this,b=arguments;if(a.url&&a.url.match(ad))Tc.apply(a,b);else{if("onloadend"in a)a.addEventListener("loadend",function(){4==(0,m.Rc)(a)&&$c(!0)},!1);else{var c=a.onreadystatechange;a.onreadystatechange=function(){4==(0,m.Rc)(a)&&$c(!0);c&&c.apply(this,arguments)}}bd.push(function(){Tc.apply(a,b)});$c()}};
var $c=function(a){a&&(cd=!1,(0,m.y)(dd));if(!cd&&bd.length)if(Uc&&!ed())(0,m.y)(fd),fd=(0,m.x)($c,100);else{cd=!0;a=bd.shift();try{a()}catch(b){$c(!0)}dd=(0,m.x)((0,m.t)($c,!0),5E3)}};
var ed=function(){var a=Uc,b=(0,m.q)("yt.player.getPlayerByElement");if(!b)return!0;var b=b("player-api"),c=(0,m.w)("ADS_DATA");return b&&(!c||!c.show_instream)&&b.getVideoLoadedFraction&&b.getDuration&&b.getCurrentTime&&b.getPlayerState?(c=b.getVideoLoadedFraction()*b.getDuration()-b.getCurrentTime(),0>=b.getPlayerState()||c>a||.3<b.getVideoLoadedFraction()):!0};m.K=function(a,b){return a?a.dataset?a.dataset[(0,m.gd)(b)]:a.getAttribute("data-"+b):null};
m.hd=function(a,b){return a?a.dataset?(0,m.gd)(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};m.gd=function(a){return id[a]||(id[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};m.jd=function(a,b){var c=(0,m.kd)(a);window.spf.script.load(a,c,b)};m.ld=function(a,b){var c=(0,m.kd)(a);window.spf.script.ignore(c,b)};
m.md=function(a){a&&((0,m.r)(a)?(0,m.jd)(a):(0,m.ia)(a)?(0,m.A)(a,function(a){(0,m.md)(a)}):(0,m.vb)(a,function(a,c){(0,m.jd)(c,function(){(0,m.md)(a)})}))};m.kd=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(nd,""),b=b.replace(od,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};
var pd=function(a){a=a||{};this.url=a.url||"";this.urlV8=a.url_v8||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||(0,m.yb)(qd);this.assets=a.assets||{};this.attrs=a.attrs||(0,m.yb)(rd);this.params=a.params||(0,m.yb)(sd);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded};m.td=function(a){a instanceof pd||(a=new pd(a));return a};m.ud=function(a){this.b=a};
m.vd=function(a){a=(a.b.cookie||"").split(m.wd);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,wk:c}};m.xd=function(a,b,c){m.yd.set(""+a,b,c,"/","youtube.com")};m.zd=function(a,b){return m.yd.get(""+a,b)};
var Ad=function(a){a=(0,m.Bd)(a);a=null===a?null:a.split(".").reverse();return(null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};m.Cd=function(a,b,c){var d=(0,m.gc)(a);if(d==(0,m.gc)(window.location.href)||!d&&0==a.lastIndexOf("/",0))if(a=(0,m.ic)(a),d=a.indexOf("#"),a=0>d?a:a.substr(0,d))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&Dd(a,b,c)):Dd(a,b)};
var Dd=function(a,b,c){for(var d=0,e=0;e<a.length;++e)d=31*d+a.charCodeAt(e),d%=4294967296;a="s_tempdata-"+d;c=c||5;b=b?(0,m.nc)(b):"";(0,m.xd)(a,b,c)};m.Ed=function(a,b,c){c=c||"";window.location=(0,m.oc)(a,b||{})+c};m.Fd=function(a){(window.ytspf||{}).enabled?window.spf.navigate(a):(0,m.Ed)(a)};m.Gd=function(a,b,c){var d=(0,m.w)("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&(0,m.Cd)(a,b);if(c)return!1;(0,m.Fd)(a);return!0};
m.Hd=function(a,b,c){a.timeOfStartCall=(new Date).getTime();if(b&&JSON&&JSON.stringify){var d=JSON.stringify(b);200>=d.length&&(a.psdJson=d)}d=c||m.p;d.GOOGLE_FEEDBACK_START_ARGUMENTS=arguments;var e=a.serverUri||"//www.google.com/tools/feedback",f=d.GOOGLE_FEEDBACK_START;if(f)f.apply(d,arguments);else{var e=e+"/load.js?",h;for(h in a)f=a[h],null!=f&&!(0,m.ma)(f)&&(e+=(0,window.encodeURIComponent)(h)+"="+(0,window.encodeURIComponent)(f)+"&");h=d.document;d=h.createElement("script");d.src=e;h.body.appendChild(d)}};
m.Id=function(){var a=window.GOOGLE_FEEDBACK_DESTROY_FUNCTION;a&&a()};var Jd=function(a){a=a.match(/[\d]+/g);if(!a)return"";a.length=3;return a.join(".")};var Kd=function(a){return(a=a.exec(m.Ld))?a[1]:""};m.Md=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,m.A)(a.childNodes,function(a){b.appendChild((0,m.Md)(a))}):b.innerHTML=a.innerHTML;return b};
m.Nd=function(a){if(a=a||window.event){for(var b in a)b in Od||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;this.pa=a;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=b.nodeName&&b}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:a.which;
this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;"MozMousePixelScroll"==this.type?(this.wheelDeltaX=a.axis==a.HORIZONTAL_AXIS?a.detail:0,this.wheelDeltaY=a.axis==a.HORIZONTAL_AXIS?0:a.detail):window.opera?(this.wheelDeltaX=0,this.wheelDeltaY=a.detail):0==a.wheelDelta%120?"WebkitTransform"in window.document.documentElement.style?window.chrome&&0==window.navigator.platform.indexOf("Mac")?(this.wheelDeltaX=a.wheelDeltaX/
-30,this.wheelDeltaY=a.wheelDeltaY/-30):(this.wheelDeltaX=a.wheelDeltaX/-1.2,this.wheelDeltaY=a.wheelDeltaY/-1.2):(this.wheelDeltaX=0,this.wheelDeltaY=a.wheelDelta/-1.6):(this.wheelDeltaX=a.wheelDeltaX/-3,this.wheelDeltaY=a.wheelDeltaY/-3);this.Wh=a.pageX;this.Xh=a.pageY}};m.Pd=function(a,b,c,d){return(0,m.xb)(m.Qd,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
m.L=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=(0,m.Pd)(a,b,c,d);if(e)return e;var e=++Rd.count+"",f=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),h;h=f?function(d){d=new m.Nd(d);if(!(0,m.Yb)(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new m.Nd(b);b.currentTarget=a;return c.call(a,b)};h=(0,m.ab)(h);m.Qd[e]=[a,b,c,h,d];a.addEventListener?"mouseenter"==b&&
f?a.addEventListener("mouseover",h,d):"mouseleave"==b&&f?a.addEventListener("mouseout",h,d):"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style?a.addEventListener("MozMousePixelScroll",h,d):a.addEventListener(b,h,d):a.attachEvent("on"+b,h);return e};m.M=function(a){a&&("string"==typeof a&&(a=[a]),(0,m.A)(a,function(a){if(a in m.Qd){var c=m.Qd[a],d=c[0],e=c[1],f=c[3],c=c[4];d.removeEventListener?d.removeEventListener(e,f,c):d.detachEvent&&d.detachEvent("on"+e,f);delete m.Qd[a]}}))};
var Sd=function(){this.j=this.g=this.b=0;this.k="";var a=(0,m.q)("window.navigator.plugins"),b=(0,m.q)("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,f=c.length;e<f;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==
a.charAt(0)||"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.k=b;b=a;this.b=b[0];this.g=b[1];this.j=b[2];if(0>=this.b){var h,k,n,u;if(m.Td)try{h=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(E){h=null}else n=window.document.body,u=window.document.createElement("object"),u.setAttribute("type","application/x-shockwave-flash"),h=n.appendChild(u);if(h&&"GetVariable"in h)try{k=h.GetVariable("$version")}catch(Q){k=""}n&&u&&n.removeChild(u);(h=k||
"")?(h=h.split(" ")[1].split(","),h=[(0,window.parseInt)(h[0],10)||0,(0,window.parseInt)(h[1],10)||0,(0,window.parseInt)(h[2],10)||0]):h=[0,0,0];this.b=h[0];this.g=h[1];this.j=h[2]}};var Ud=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.b>b[0]||a.b==b[0]&&a.g>b[1]||a.b==b[0]&&a.g==b[1]&&a.j>=b[2]};
var Vd=function(a){return-1<a.k.indexOf("Gnash")&&-1==a.k.indexOf("AVM2")||9==a.b&&1==a.g||9==a.b&&0==a.g&&1==a.j?!1:9<=a.b};var Wd=function(a){return m.Xd?!Ud(a,11,2):m.Yd?!Ud(a,11,3):!Vd(a)};m.Zd=function(){return m.$d?"Webkit":m.ae?"Moz":m.G?"ms":m.be?"O":null};m.ce=function(){return m.$d?"-webkit":m.ae?"-moz":m.G?"-ms":m.be?"-o":null};m.de=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
m.ee=function(a,b){return a&&b?b instanceof m.de?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};m.fe=function(a,b){var c=(0,m.Ia)(b);if(void 0===a.style[c]){var d=(0,m.Zd)()+(0,m.Ja)(c);if(void 0!==a.style[d])return d}return c};m.ge=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};m.he=function(a,b){a.style.height=(0,m.ge)(b,!0)};m.ie=function(a,b){a.style.display=b?"":"none"};
m.je=function(){this.b="";this.g=ke};var le=function(a){return a instanceof m.je&&a.constructor===m.je&&a.g===ke?a.b:"type_error:Const"};var me=function(){this.b="";this.g=ne};var oe=function(a){var b=new me;b.b=a;return b};var pe=function(){this.b=qe};var re=function(){this.b="";this.j=se;this.g=null};m.te=function(a){return a instanceof re&&a.constructor===re&&a.j===se?a.b:"type_error:SafeHtml"};
m.ue=function(a,b){if(!ve.test(a))throw Error("Invalid tag name <"+a+">.");if(a.toLowerCase()in we)throw Error("Tag name <"+a+"> is not allowed for SafeHtml.");var c=null,d="<"+a;if(b)for(var e in b){if(!ve.test(e))throw Error('Invalid attribute name "'+e+'".');var f=b[e];if(null!=f){if(f instanceof m.je)f=le(f);else if("style"==e.toLowerCase()){if(!(0,m.ma)(f))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof f+" given: "+f);if(!(f instanceof me)){var h=
"",k=void 0;for(k in f){if(!/^[-_a-zA-Z0-9]+$/.test(k))throw Error("Name allows only [-_a-zA-Z0-9], got: "+k);var n=f[k];null!=n&&(n instanceof m.je?n=le(n):xe.test(n)||(n="zClosurez"),h+=k+":"+n+";")}f=h?oe(h):ye}f=f instanceof me&&f.constructor===me&&f.g===ne?f.b:"type_error:SafeStyle"}else{if(/^on/i.test(e))throw Error('Attribute "'+e+'" requires goog.string.Const value, "'+f+'" given.');if(f instanceof pe)f=f instanceof pe&&f.constructor===pe&&f.b===qe?"":"type_error:SafeUrl";else if(e.toLowerCase()in
ze)throw Error('Attribute "'+e+'" requires goog.string.Const or goog.html.SafeUrl value, "'+f+'" given.');}d+=" "+e+'="'+(0,m.wa)(String(f))+'"'}}e=void 0;(0,m.ca)(e)?(0,m.ia)(e)||(e=[e]):e=[];!0===Ae[a.toLowerCase()]?d+=">":(c=Be(e),d+=">"+(0,m.te)(c)+"</"+a+">",c=c.Hf());(e=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(e)?c=0:c=null);return Ce(d,c)};
var Be=function(a){function b(a){if((0,m.ia)(a))(0,m.A)(a,b);else{if(!(a instanceof re)){var f=null;a.Ul&&(f=a.Hf());a=Ce((0,m.wa)(a.qg?a.pg():String(a)),f)}d+=(0,m.te)(a);a=a.Hf();0==c?c=a:0!=a&&c!=a&&(c=null)}}var c=0,d="";(0,m.A)(arguments,b);return Ce(d,c)};var Ce=function(a,b){var c=new re;c.b=a;c.g=b;return c};m.De=function(a,b){(a=(0,m.H)(a))&&a.style&&((0,m.ie)(a,b),(0,m.sb)(a,"hid",!b))};m.N=function(a){(0,m.A)(arguments,function(a){(0,m.De)(a,!0)})};
m.Ee=function(a){var b=m.Fe,c=(0,m.w)("FEEDBACK_LOCALE_EXTRAS",{});a?(0,m.zb)(b,a):(0,m.zb)(b,c);return b};m.Ge=function(a){var b=(0,m.w)("SESSION_INDEX"),c=(0,m.w)("FEEDBACK_BUCKET_ID");a={abuseLink:"https://support.google.com/youtube/bin/answer.py?answer=140536",customZIndex:"2000000005",locale:(0,m.w)("FEEDBACK_LOCALE_LANGUAGE"),productId:(a||"59")+""};b&&(a.authuser=b+"");c&&(a.bucket=c);return a};
m.He=function(a,b){try{var c=(0,m.Ee)(b);try{var d,e=(0,m.q)("yt.player.getPlayerByElement");(d=e?e("player-api"):null)&&d.pauseVideo&&d.pauseVideo();var f=Sd.getInstance();c.flashVersion=f.getVersion().join(".");d&&(c.playback_id=d.getVideoData().cpn)}catch(h){}var k=(0,m.Ge)(a);(0,m.Id)();(0,m.Hd)(k,c);return!1}catch(n){return!0}};m.Ie=function(){var a=(0,m.zd)("PREF");if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(m.Je[d]=c.toString())}};
var Ke=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};var Le=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};m.Me=function(a){a=void 0!==m.Je[a]?m.Je[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};m.Ne=function(a,b){return!!(((0,m.Me)("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
var Oe=function(a,b,c){if(b){a=(0,m.r)(a)?(0,m.Jb)(a):a;c=(0,m.td)(c);var d=(0,m.yb)(c.attrs);d.tabindex=0;var e=(0,m.yb)(c.params);e.flashvars=(0,m.nc)(c.args);if(m.Td){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var f in d)b.setAttribute(f,d[f]);for(f in e)d=window.document.createElement("param"),d.setAttribute("name",f),d.setAttribute("value",e[f]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");
b.setAttribute("name",d.id);for(f in d)b.setAttribute(f,d[f]);for(f in e)b.setAttribute(f,e[f])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};m.Pe=function(a,b){a=(0,m.r)(a)?(0,m.Jb)(a):a;b=(0,m.td)(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=Qe();Ud(c,b.minVersion)?(c=Re(b,c),Oe(a,c,b)):Se(a,b,c)};
var Te=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=(0,m.td)(a);var d=!!b,e=(0,m.H)(a.attrs.id),f=e?e.parentNode:null;if(e&&f){if(window!=window.top){var h=null;if(window.document.referrer){var k=window.document.referrer.substring(0,128);Ad(k)||(h=k)}else h="unknown";h&&(d=!0,a.args.framer=h)}h=Qe();if(Ud(h,a.minVersion)){var k=Re(a,h),n="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(n=e.getAttribute("src")||e.movie);(n!=k||d)&&Oe(f,k,a);Wd(h)&&Ue()}else Se(f,a,h);c&&c()}else(0,m.x)(function(){Te(a,
b,c)},50)}};var Se=function(a,b,c){0==c.b&&b.fallback?b.fallback():0==c.b&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+(0,m.hb)("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};var Re=function(a,b){var c;(c=Vd(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!Ud(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.urlV8||a.url};
var Qe=function(){var a=Sd.getInstance(),b=m.Ie.getInstance();b.set("fv",a.getVersion().join("."));b.save();return a};var Ue=function(){var a=(0,m.H)("flash10-promo-div"),b=(0,m.Ne)(m.Ie.getInstance(),107);a&&!b&&(0,m.N)(a)};m.Ve=function(a){var b=a.match(We);window.spf.style.load(a,b?b[1]:"",void 0)};
var Xe=function(){if(2.2==Ye)return!0;var a;a=(0,m.q)("yt.player.utils.videoElement_");a||(a=window.document.createElement("video"),(0,m.l)("yt.player.utils.videoElement_",a,void 0));try{return!(!a||!a.canPlayType||!a.canPlayType('video/mp4; codecs="avc1.42001E, mp4a.40.2"')&&!a.canPlayType('video/webm; codecs="vp8.0, vorbis"'))}catch(b){return!1}};var Ze=function(){};m.$e=function(){};m.af=function(a){this.b=a};m.bf=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.b=a};
var cf=function(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.b=a};m.df=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};m.ef=function(a){return(0,m.ff)(new m.gf(void 0),a)};
m.gf=function(a){this.b=a};m.ff=function(a,b){var c=[];hf(a,b,c);return c.join("")};
var hf=function(a,b,c){switch(typeof b){case "string":jf(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if((0,m.ia)(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],hf(a,a.b?a.b.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=
typeof e&&(c.push(d),jf(f,c),c.push(":"),hf(a,a.b?a.b.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}};var jf=function(a,b){b.push('"',a.replace(kf,function(a){if(a in lf)return lf[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return lf[a]=e+b.toString(16)}),'"')};var mf=function(a){this.b=a};var nf=function(a){this.b=a};var of=function(a){this.data=a};
var pf=function(a){return!(0,m.ca)(a)||a instanceof of?a:new of(a)};m.qf=function(a){a=a.data;if(!(0,m.ca)(a))throw"Storage: Invalid value was encountered";return a};var rf=function(a){this.b=a};m.sf=function(a){var b=a.creation;a=a.expiration;return!!a&&a<(0,m.J)()||!!b&&b>(0,m.J)()};m.tf=function(a){this.b=a};m.uf=function(a,b,c){var d=c&&0<c?c:0;c=d?(0,m.J)()+1E3*d:0;if((d=d?m.vf:m.wf)&&window.JSON){(0,m.r)(b)||(b=JSON.stringify(b,void 0));try{d.set(a,b,c)}catch(e){d.remove(a)}}};
m.xf=function(a){if(!m.wf&&!m.vf||!window.JSON)return null;var b;try{b=m.wf.get(a)}catch(c){}if(!(0,m.r)(b))try{b=m.vf.get(a)}catch(d){}if(!(0,m.r)(b))return null;try{b=JSON.parse(b,void 0)}catch(e){}return b};var yf=function(){var a={volume:100,muted:!1},b=(0,m.xf)("yt-player-volume")||{};a.volume=(0,window.isNaN)(b.volume)?100:(0,m.ub)(b.volume,0,100);a.muted=void 0==b.muted?!1:b.muted;return a};
var zf=function(a,b){this.j=this.Hc=a;this.J=b;this.B=!1;this.b={};this.S=this.F=null;this.N=new m.Xa;(0,m.Ua)(this,this.N);this.k={};this.A=this.V=this.g=this.la=this.T=null;this.O=!1;this.ea=this.D=null;this.da={};this.Xa=["onReady"];this.Fa=null;this.Sa=0;if(this.C=!!(0,m.w)("PLAYER_ENABLE_SHARED_UI"))this.Hc=window.document.createElement("div"),this.j.appendChild(this.Hc),this.j.style.position="relative";this.ha=!1;this.Da=!!(0,m.w)("PLAYER_PERSISTENCE_REFACTOR");Af(this);this.yd("onVolumeChange",
(0,m.s)(this.vm,this));this.yd("onError",(0,m.s)(this.um,this));this.yd("onTabOrderChange",(0,m.s)(this.tm,this));this.yd("WATCH_LATER_VIDEO_ADDED",(0,m.s)(this.wm,this));this.yd("WATCH_LATER_VIDEO_REMOVED",(0,m.s)(this.xm,this))};
var Bf=function(a,b){a.la=b;a.T=b.clone();a.g=a.T.attrs.id||a.g;"video-player"==a.g&&(a.g=a.J,a.T.attrs.id=a.J);a.j.id==a.g&&(a.g=a.g+"-player",a.T.attrs.id=a.g);var c=a.T.args,d;if(!(d=a.T.args.eurl)){d=window.document.location.toString();var e=!!d&&-1!=d.search(Cf),f=-1!=d.indexOf("/embed/");e!=f&&(0,m.db)(Error(d+" behavior is not consistent"));d=f?window.document.referrer&&window.document.referrer.substring(0,128)||"unknown":d}c.eurl=d;a.T.args.enablejsapi="1";a.T.args.playerapiid=a.J;a.V||(a.V=
Df(a,a.T.args.jsapicallback||"onYouTubePlayerReady"));a.T.args.jsapicallback=null;a.C&&(a.T.args.controls="0");if(c=a.T.attrs.width)a.j.style.width=(0,m.ge)(Number(c)||c,!0);(c=a.T.attrs.height)&&(0,m.he)(a.j,Number(c)||c);a.j.style.overflow="hidden"};var Ef=function(a){a.T.loaded||(a.T.loaded=!0,"0"!=a.T.args.autoplay?a.b.loadVideoByPlayerVars(a.T.args):a.b.cueVideoByPlayerVars(a.T.args))};var Ff=function(a){if(!(0,m.ca)(a.T.disable.flash)){var b=a.T.disable,c;c=Ud(Qe(),a.T.minVersion);b.flash=!c}return!a.T.disable.flash};
var Gf=function(a){var b=(0,m.H)(a.g);b&&b.stopVideo&&b.stopVideo();if(Ff(a)){var c=a.T;b&&b.getUpdatedConfigurationData&&(b=(0,m.td)(b.getUpdatedConfigurationData()),b.args.video_id==c.args.video_id&&(c=b));c.args.autoplay=1;c.args.html5_unavailable="1";Bf(a,c);Hf(a,"flash")}};
var Hf=function(a,b){if(!a.ca()){if(!b){var c;if(!(c=!a.T.html5&&Ff(a))){if(!(0,m.ca)(a.T.disable.html5)){if(c=Xe())c=If(a)||a.T.assets.js;a.T.disable.html5=!c;c||(a.T.args.html5_unavailable="1")}c=!!a.T.disable.html5}b=c?Ff(a)?"flash":"unsupported":"html5"}("flash"==b?a.Hs:"html5"==b?a.Is:a.Js).call(a);a.C&&!a.ha&&Jf(a)}};var If=function(a){var b=!0;a.Da&&((b=(0,m.H)(a.g))&&a.T?(a=a.T,a=(0,m.K)(b,"version")==a.assets.js):a=!1,b=a);return b&&!!(0,m.q)("yt.player.Application.create")};
var Kf=function(a,b,c){var d=b[c];return function(){try{return a.Fa=null,d.apply(b,arguments)}catch(e){e.message+=" ("+c+")",a.Fa=e,(0,m.db)(e,"WARNING")}}};
var Af=function(a){a.B=!1;if(a.S)for(var b in a.k)a.S(b,a.k[b]);a.F=null;a.S=null;for(var c in a.b)a.b[c]=null;a.b.addEventListener=(0,m.s)(a.yd,a);a.b.removeEventListener=(0,m.s)(a.Pp,a);a.b.destroy=(0,m.s)(a.dispose,a);a.b.getLastError=(0,m.s)(a.Np,a);a.b.getPlayerType=(0,m.s)(a.Op,a);a.b.getCurrentVideoConfig=(0,m.s)(a.Mp,a);a.b.loadNewVideoConfig=(0,m.s)(a.dh,a);a.b.isReady=(0,m.s)(a.Qp,a)};
var Df=function(a,b){var c=b;if("string"==typeof b){if(a.da[b])return a.da[b];c=function(){var a=(0,m.q)(b);a&&a.apply(m.p,arguments)};a.da[b]=c}return c?c:null};var Lf=function(a,b){var c="ytPlayer"+b+a.J;a.k[b]=c;m.p[c]=function(c){(0,m.x)(function(){a.ca()||a.N.U(b,c)},0)};return c};var Mf=function(a){return(a=(0,m.H)(a.g))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
var Nf=function(a){a.cancel();Af(a);a.A=null;a.T.loaded=!1;var b=(0,m.H)(a.g);"html5"==Mf(a)?a.ea=b:b&&b.destroy&&b.destroy();a.C&&(0,m.Ub)((0,m.H)(a.g));(0,m.Tb)(a.Hc)};var Jf=function(a){a.T.assets.js_sharedui&&(a.ha=!0,(0,m.Ve)(a.T.assets.css_sharedui),(0,m.jd)(a.T.assets.js_sharedui,(0,m.s)(function(){this.b.addEventListener("onReady",(0,m.s)(this.Dq,this))},a)))};
m.Of=function(a,b){a=(0,m.r)(a)?(0,m.Jb)(a):a;b=(0,m.td)(b);var c="player"+(0,m.na)(a),d=Pf[c];if(d)return d.dh(b),d.b;d||(d=new zf(a,c),Pf[c]=d,(0,m.B)("player-added",d.b),(0,m.Va)(d,(0,m.t)(Qf,d)));(0,m.x)(function(){d.dh(b)},0);return d.b};var Rf=function(){for(var a in Pf){var b=Pf[a];b&&b.cancel()}};m.Sf=function(a){if(a=(0,m.H)(a))a="player"+(0,m.na)(a),(a=Pf[a])&&a.dispose()};var Qf=function(a){Pf[a.getId()]=null};
m.Tf=function(a){a=(0,m.H)(a);if(!a)return null;var b="player"+(0,m.na)(a),c=Pf[b];c||(c=new zf(a,b),Pf[b]=c);return c.b};
var Uf=function(){(0,m.l)("yt.player.exports.navigate",m.Gd,void 0);(0,m.l)("yt.player.embed",m.Of,void 0);(0,m.l)("yt.player.destroy",m.Sf,void 0);(0,m.l)("yt.player.cancelAll",Rf,void 0);(0,m.l)("yt.player.getPlayerByElement",m.Tf,void 0);(0,m.l)("yt.player.exports.feedbackStart",m.He,void 0);Vf=Vf||!!(0,m.w)("PLAYER_WATCH_WHILE")||!!(0,m.zd)("watch_while");var a=(0,m.q)("ytplayer.config");Wf(a);(0,m.q)("ytspf.enabled")&&(Xf=(0,m.bb)(Yf,5E3),(a=(0,m.Zf)())?(a.addEventListener("onReady",Yf),a.addEventListener("onStateChange",
Yf),Vf&&(a.addEventListener("onReady",$f),a.addEventListener("onStateChange",$f))):ag("unable to init PP monitor"))};var Wf=function(a){Rf();if(a=a||null){var b=(0,m.Zf)(),c=!0;b&&b.getVideoData&&(c=b.getVideoData(),c=c.video_id!=a.args.video_id||c.list!=a.args.list);c?(bg="",(0,m.Of)("player-api",a)):b.playVideo();a=(0,m.td)(a);a.loaded=!0}$f();Yf();(0,m.l)("ytplayer.config",a,void 0)};m.Zf=function(){var a=(0,m.q)("yt.player.getPlayerByElement");return a?a("player-api"):null};
var Yf=function(){var a=(0,m.C)((0,m.H)("player"),"off-screen"),b=(0,m.Zf)(),b=1==(b&&b.isReady()?b.getPlayerState():void 0),c="watch"==(0,m.w)("PAGE_NAME");cg&&!Vf&&b&&ag("minimized PP playing");a&&c?ag("PP off-screen on watch"):Vf||a||c||ag("PP !off-screen off watch")};var $f=function(){if(Vf){var a="watch"==(0,m.w)("PAGE_NAME"),b=(0,m.Zf)();1==(b&&b.isReady()?b.getPlayerState():void 0)?dg(!0):a&&dg(!1);eg()}};
var eg=function(){var a=(0,m.H)("player"),b=(0,m.H)("player-mole-container");cg=!a||(0,m.C)(a,"off-screen")||!b||(0,m.C)(b,"watch-mole");(a=(0,m.Zf)())&&a.isReady()&&a.setMinimized(cg)};var ag=function(a){var b=(0,m.w)("PAGE_NAME");b&&(b=[b,bg,(0,m.q)("_spf_state.nav-counter")],a+="("+b.join(",")+")",(0,m.l)("yt.www.persistentplayer.issue",a,void 0),(0,m.db)(Error(a),"WARNING"))};var dg=function(a){(0,m.sb)((0,m.H)("player-mole-container"),"video-mole",a);eg()};
var fg=function(){(0,m.tc)("ol");gg("init");var a=(0,m.w)("PAGE_NAME");a&&gg("init-"+a);Gc()};var gg=function(a){(0,m.Hc)()?hg.push((0,m.Jc)((0,m.t)(m.ob,a),0)):(0,m.B)(a)};var ig=function(){(0,m.Lc)(hg);hg.length=0;var a=(0,m.w)("PAGE_NAME");a&&(0,m.ob)("dispose-"+a);(0,m.ob)("dispose")};var jg=function(){fg()};var kg=function(){(0,m.w)("TIMING_REPORT_ON_UNLOAD")&&Fc(!0);ig()};
var lg=function(a,b,c){for(var d=window.document.getElementsByTagName("script"),e=!1,f=0,h=d.length;f<h;f++)if(0<d[f].src.indexOf("/debug-")){e=!0;break}e&&(d=Error(),d.message=a,d.fileName=b,d.lineNumber=c,(0,m.db)(d))};var mg=function(){ng=1;(0,m.w)("TIMING_REPORT_ON_UNLOAD")&&Fc(!0);Ac(void 0);Bc();og=0;vc("mark_navigation_requested");pg(qg);(0,m.ob)("navigate")};
var rg=function(a){a=a.detail.part;(0,m.tc)("nc"+og);++og;var b=1==ng;ng=2;b?(pg(sg),tg()):pg(ug);(a.data&&a.data.swfcfg||a.swfcfg)&&vg(a.data&&a.data.swfcfg||a.swfcfg)};var wg=function(){};
var xg=function(a){a=a.detail.response;var b=1==ng;ng=3;var c=window._spf_state,c=c&&c["nav-counter"]||0;xc(void 0).info.yt_nav=c;(0,m.tc)("_start",a.timing.responseStart);c=a.timing;c=Math.max(0,c.responseStart-c.navigationStart);xc(void 0).info.srt=c;c=a.timing.spfPrefetchType||"none";xc(void 0).info.yt_pft=c;wc("req",a.timing.responseStart-a.timing.fetchStart);b&&(pg(yg),tg());(a.data&&a.data.swfcfg||a.swfcfg)&&vg(a.data&&a.data.swfcfg||a.swfcfg)};
var zg=function(){pg(Ag);window.document.getElementById("content").style.height="";fg();ng=0};var Bg=function(a){var b=a.detail.err;b&&b.message&&(b.message+=" (url: "+a.detail.url+")");(0,m.db)(b)};var Cg=function(){Dg()};var Eg=function(){};
var tg=function(){window.scroll(0,0);var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");ig();for(var b in m.$a)delete m.$a[b];(0,m.l)("ytplayer.config",null,void 0);if(!Vf)if((a=(0,m.Zf)())&&a.stopVideo){if(a.stopVideo(),a=a.getLastError())bg=a,(a=(0,m.H)("movie_player"))&&a.stopVideo?(a.stopVideo(),bg="recovered"):bg="missing2"}else bg="missing";Yf()};var vg=function(a){"cfg"in uc(void 0)||(0,m.tc)("cfg");Wf(a)};
var pg=function(a){function b(){var b=a[0],e=a[1],f=a[2];c.className="";var h=c.style;h.transitionDuration=h.webkitTransitionDuration=b+"ms";h.width=e+"%";(0,m.y)(Fg);Fg=(0,m.x)(function(){c.className=f},b)}var c=window.document.getElementById("progress");c||(c=window.document.createElement("div"),c.id="progress",c.innerHTML="<dt><dd>",window.document.body.appendChild(c));(0,m.Ic)()?(0,m.Jc)(b,0):(0,m.x)(b,0)};
var Dg=function(){var a=Ag[0]+50;(0,m.y)(Fg);Fg=(0,m.x)(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};
var Gg=function(){"watch"!=(0,m.w)("PAGE_NAME")&&(0,m.l)("yt.www.skywatch.lastBrowsePage",window.location.href,void 0);if((0,m.w)("SKYWATCH_ENABLED")){var a=(0,m.H)("skywatch-close-button");a||(a=window.document.createElement("button"),(0,m.qb)(a,["yt-uix-button","yt-uix-button-default"]),a.id="skywatch-minimize-button",a.innerHTML="\u21f2",(0,m.H)("player-mole-container").appendChild(a));Hg.push((0,m.L)(a,"click",Ig))}};var Ig=function(){(0,m.Fd)((0,m.q)("yt.www.skywatch.lastBrowsePage")||"/")};
var Jg=function(){m.Mc.call(this,"www/base");this.b=0};var Kg=function(a){(a=a.detail.name)&&Qc(a)};m.ba=[];m.Lg=m.Lg||{};m.p=this;oa="closure_uid_"+(1E9*Math.random()>>>0);pa=0;m.J=Date.now||function(){return+new Date};Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return m.s.apply(null,c)}return(0,m.s)(this,a)};m.sa[" "]=m.ea;(0,m.v)(m.ta,Error);m.ta.prototype.name="CustomError";var ya=/&/g,za=/</g,Aa=/>/g,Ba=/"/g,Ca=/'/g,Da=/\x00/g,xa=/[\x00&<>"']/;m.Qa=Array.prototype;m.Na=m.Qa.indexOf?function(a,b,c){return m.Qa.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if((0,m.r)(a))return(0,m.r)(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
m.Mg=m.Qa.lastIndexOf?function(a,b,c){return m.Qa.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if((0,m.r)(a))return(0,m.r)(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};m.A=m.Qa.forEach?function(a,b,c){m.Qa.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,m.r)(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
m.rb=m.Qa.filter?function(a,b,c){return m.Qa.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=(0,m.r)(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var n=h[k];b.call(c,n,k,a)&&(e[f++]=n)}return e};m.Ng=m.Qa.map?function(a,b,c){return m.Qa.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=(0,m.r)(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
m.Og=m.Qa.reduce?function(a,b,c,d){d&&(b=(0,m.s)(b,d));return m.Qa.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,m.A)(a,function(c,h){e=b.call(d,e,c,h,a)});return e};m.Pg=m.Qa.some?function(a,b,c){return m.Qa.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,m.r)(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
m.Qg=m.Qa.every?function(a,b,c){return m.Qa.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,m.r)(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};m.Ta.prototype.Ph=!1;m.Ta.prototype.ca=function(){return this.Ph};m.Ta.prototype.dispose=function(){this.Ph||(this.Ph=!0,this.K())};m.Ta.prototype.K=function(){if(this.za)for(;this.za.length;)this.za.shift()()};(0,m.v)(m.Xa,m.Ta);m.g=m.Xa.prototype;m.g.rk=1;m.g.Gf=0;m.g.subscribe=function(a,b,c){var d=this.kb[a];d||(d=this.kb[a]=[]);var e=this.rk;this.b[e]=a;this.b[e+1]=b;this.b[e+2]=c;this.rk=e+3;d.push(e);return e};m.g.Rc=function(a,b,c){if(a=this.kb[a]){var d=this.b;if(a=(0,m.Ka)(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.qb(a)}return!1};
m.g.qb=function(a){if(0!=this.Gf)return this.g||(this.g=[]),this.g.push(a),!1;var b=this.b[a];if(b){var c=this.kb[b];c&&(0,m.Oa)(c,a);delete this.b[a];delete this.b[a+1];delete this.b[a+2]}return!!b};m.g.U=function(a,b){var c=this.kb[a];if(c){this.Gf++;for(var d=(0,m.Sa)(arguments,1),e=0,f=c.length;e<f;e++){var h=c[e];this.b[h+1].apply(this.b[h+2],d)}this.Gf--;if(this.g&&0==this.Gf)for(;c=this.g.pop();)this.qb(c);return 0!=e}return!1};
m.g.clear=function(a){if(a){var b=this.kb[a];b&&((0,m.A)(b,this.qb,this),delete this.kb[a])}else this.b.length=0,this.kb={}};m.g.ka=(0,m.aa)(3);m.g.K=function(){m.Xa.H.K.call(this);delete this.b;delete this.kb;delete this.g};m.$a=window.yt&&window.yt.config_||{};(0,m.l)("yt.config_",m.$a,void 0);(0,m.l)("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);m.fb=window.yt&&window.yt.msgs_||{};(0,m.l)("yt.msgs_",m.fb,void 0);m.Td="Microsoft Internet Explorer"==window.navigator.appName;var Rg=(0,m.q)("yt.pubsub.instance_")||new m.Xa;m.Xa.prototype.subscribe=m.Xa.prototype.subscribe;m.Xa.prototype.unsubscribeByKey=m.Xa.prototype.qb;m.Xa.prototype.publish=m.Xa.prototype.U;m.Xa.prototype.clear=m.Xa.prototype.clear;(0,m.l)("yt.pubsub.instance_",Rg,void 0);var kb=(0,m.q)("yt.pubsub.subscribedKeys_")||{};(0,m.l)("yt.pubsub.subscribedKeys_",kb,void 0);var mb=(0,m.q)("yt.pubsub.topicToKeys_")||{};(0,m.l)("yt.pubsub.topicToKeys_",mb,void 0);var lb=(0,m.q)("yt.pubsub.isSynchronous_")||{};
(0,m.l)("yt.pubsub.isSynchronous_",lb,void 0);m.jb=(0,m.q)("yt.pubsub.skipSubId_")||null;(0,m.l)("yt.pubsub.skipSubId_",m.jb,void 0);var Ab="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");t:{var Sg=m.p.navigator;if(Sg){var Tg=Sg.userAgent;if(Tg){m.Ld=Tg;break t}}m.Ld=""};var Ib;var bh;var Fb;var Gb;m.be=(0,m.Ea)(m.Ld,"Opera")||(0,m.Ea)(m.Ld,"OPR");m.G=(0,m.Ea)(m.Ld,"Trident")||(0,m.Ea)(m.Ld,"MSIE");m.ae=(0,m.Ea)(m.Ld,"Gecko")&&!(0,m.Ea)(m.Ld.toLowerCase(),"webkit")&&!((0,m.Ea)(m.Ld,"Trident")||(0,m.Ea)(m.Ld,"MSIE"));m.$d=(0,m.Ea)(m.Ld.toLowerCase(),"webkit");m.$d&&(0,m.Ea)(m.Ld,"Mobile");var Yg=Cb(),Zg=Yg&&Yg.platform||"";m.Yd=(0,m.Ea)(Zg,"Mac");m.Xd=(0,m.Ea)(Zg,"Win");m.Ug=(0,m.Ea)(Zg,"Linux");m.Vg=!!Cb()&&(0,m.Ea)(Cb().appVersion||"","X11");var $g=m.Ld;
m.Wg=!!$g&&(0,m.Ea)($g,"Android");m.Xg=!!$g&&(0,m.Ea)($g,"iPhone");m.ah=!!$g&&(0,m.Ea)($g,"iPad");Gb=function(){var a="",b;if(m.be&&m.p.opera)return a=m.p.opera.version,(0,m.la)(a)?a():a;m.ae?b=/rv\:([^\);]+)(\)|;)/:m.G?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:m.$d&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(m.Ld))?a[1]:"");return m.G&&(b=Db(),b>(0,window.parseFloat)(a))?String(b):a}();Fb={};bh=m.p.document;Ib=bh&&m.G?Db()||("CSS1Compat"==bh.compatMode?(0,window.parseInt)(Gb,10):5):void 0;var Qb;Qb=!m.G||(0,m.Hb)(9);m.ch=!m.ae&&!m.G||m.G&&(0,m.Hb)(9)||m.ae&&(0,m.Eb)("1.9.1");m.dh=m.G&&!(0,m.Eb)("9");m.eh=m.G||m.be||m.$d;var Mb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};m.ac="StopIteration"in m.p?m.p.StopIteration:Error("StopIteration");m.Zb.prototype.next=function(){throw m.ac;};m.Zb.prototype.Ta=function(){return this};var hc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,fc=m.$d;var Cf=/^https?:\/\/([A-Za-z0-9-]{1,63}\.)*(corp\.google\.com|prod\.google\.com|video\.google\.com|youtube\.com|youtube\.googleapis\.com|youtube-nocookie\.com|youtubeeducation\.com)(:[0-9]+)?\/embed\//;var sc={},rc=0,fh=(0,m.q)("yt.net.ping.workerUrl_")||null;(0,m.l)("yt.net.ping.workerUrl_",fh,void 0);var Dc,Cc=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},Bc=(0,m.s)(Cc.clearResourceTimings||Cc.webkitClearResourceTimings||Cc.mozClearResourceTimings||Cc.msClearResourceTimings||Cc.oClearResourceTimings||m.ea,Cc),vc=Cc.mark?function(a){Cc.mark(a)}:m.ea,Ec="https:"===window.location.protocol&&(0,m.la)(Cc.getEntriesByType)?function(a){var b={};Cc.getEntriesByType("resource").forEach(function(a){if(0===a.name.indexOf("https://s.ytimg.com/yts/")){var d=
gh[a.initiatorType];if(d&&d.extension.test(a.name)){var e=d.vg,d=e+"t",e=e+"c";void 0===b[d]&&(b[d]=0,b[e]=0);b[d]++;0!==a.responseStart&&a.responseStart!==a.requestStart||b[e]++}}});Object.keys(b).forEach(function(c){a["cs"+c]=b[c]})}:m.ea,gh={link:{vg:"c",extension:/\.css$/},script:{vg:"j",extension:/\.js$/},css:{vg:"s",extension:/\.(?:webp|png)$/},"":{vg:"f",extension:/\.swf$/}};m.g=m.Mc.prototype;m.g.is=function(){2==this.g||this.init()};m.g.enable=function(){this.g=1;(0,m.A)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.is,this),this.subscribe("dispose-"+a,this.dispose,this),(0,m.w)("PAGE_NAME")==a&&(0,m.Nc)(this))},this)};m.g.init=function(){this.g=2;this.B&&this.B()};m.g.dispose=function(){this.g=3;(0,m.Kc)(this.j);this.A&&this.A()};m.g.disable=function(){this.g=4;this.dispose();this.clear()};
m.g.subscribe=function(a,b,c){a=(0,m.z)(a,b,c);this.k.push(a);return a};m.g.clear=function(){(0,m.nb)(this.k);this.k=[]};var Pc=(0,m.q)("yt.modules.registry_")||{};(0,m.l)("yt.modules.registry_",Pc,void 0);m.hh=null;"undefined"!=typeof window.XMLHttpRequest?m.hh=function(){return new window.XMLHttpRequest}:"undefined"!=typeof window.ActiveXObject&&(m.hh=function(){return new window.ActiveXObject("Microsoft.XMLHTTP")});var Tc,Uc,Vc,Wc,cd,fd=0,dd=0,bd=[],ad=/.+\.googlevideo\.com|c\.youtube\.com|\/videoplayback\?|spf\=navigate/g;var id={};var nd=/-vfl[a-zA-Z0-9_+=-]+/,od=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;var qd={enablejsapi:1},rd={},sd={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};pd.prototype.clone=function(){var a=new pd,b;for(b in this){var c=this[b];"object"==(0,m.ha)(c)?a[b]=(0,m.yb)(c):a[b]=c}return a};m.wd=/\s*;\s*/;m.g=m.ud.prototype;m.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');(0,m.ca)(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,m.J)()+1E3*c)).toUTCString();this.b.cookie=a+"="+b+e+d+c+f};
m.g.get=function(a,b){for(var c=a+"=",d=(this.b.cookie||"").split(m.wd),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};m.g.remove=function(a,b,c){var d=(0,m.ca)(this.get(a));this.set(a,"",0,b,c);return d};m.g.Ja=(0,m.aa)(4);m.g.oa=(0,m.aa)(5);m.g.isEmpty=(0,m.aa)(6);m.g.ka=(0,m.aa)(2);m.g.Te=(0,m.aa)(7);m.g.clear=function(){for(var a=(0,m.vd)(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};m.yd=new m.ud(window.document);m.yd.g=3950;m.Bd=m.gc;var ih=!1,jh="";
if(window.navigator.plugins&&window.navigator.plugins.length){var kh=window.navigator.plugins["Shockwave Flash"];kh&&(ih=!0,kh.description&&(jh=Jd(kh.description)));window.navigator.plugins["Shockwave Flash 2.0"]&&(ih=!0,jh="2.0.0.11")}else if(window.navigator.mimeTypes&&window.navigator.mimeTypes.length){var lh=window.navigator.mimeTypes["application/x-shockwave-flash"];(ih=lh&&lh.enabledPlugin)&&(jh=Jd(lh.enabledPlugin.description))}else try{var mh=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),ih=
!0,jh=Jd(mh.GetVariable("$version"))}catch(nh){try{mh=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),ih=!0,jh="6.0.21"}catch(oh){try{mh=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash"),ih=!0,jh=Jd(mh.GetVariable("$version"))}catch(ph){}}}m.qh=jh;var Dh;var Ch;var Bh;var Ah;var rh,sh,th,uh,vh,wh,xh;xh=wh=vh=uh=th=sh=rh=!1;var yh=m.Ld;yh&&(-1!=yh.indexOf("Firefox")?rh=!0:-1!=yh.indexOf("Camino")?sh=!0:-1!=yh.indexOf("iPhone")||-1!=yh.indexOf("iPod")?th=!0:-1!=yh.indexOf("iPad")?uh=!0:-1!=yh.indexOf("Chrome")?wh=!0:-1!=yh.indexOf("Android")?vh=!0:-1!=yh.indexOf("Safari")&&(xh=!0));m.zh=rh;Ah=sh;Bh=th;Ch=uh;Dh=vh;m.Eh=wh;m.Fh=xh;m.Gh=function(){if(m.zh)return Kd(/Firefox\/([0-9.]+)/);if(m.G||m.be)return Gb;if(m.Eh)return Kd(/Chrome\/([0-9.]+)/);if(m.Fh)return Kd(/Version\/([0-9.]+)/);if(Bh||Ch){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(m.Ld))return a[1]+"."+a[2]}else{if(Dh)return(a=Kd(/Android\s+([0-9.]+)/))?a:Kd(/Version\/([0-9.]+)/);if(Ah)return Kd(/Camino\/([0-9.]+)/)}return""}();m.Hh=m.$d?"webkit":m.ae?"moz":m.G?"ms":m.be?"o":"";m.Ih=(0,m.q)("yt.dom.getNextId_");if(!m.Ih){m.Ih=function(){return++Jh};(0,m.l)("yt.dom.getNextId_",m.Ih,void 0);var Jh=0};m.g=m.Nd.prototype;m.g.pa=null;m.g.type="";m.g.target=null;m.g.relatedTarget=null;m.g.currentTarget=null;m.g.data=null;m.g.source=null;m.g.state=null;m.g.keyCode=0;m.g.charCode=0;m.g.altKey=!1;m.g.ctrlKey=!1;m.g.shiftKey=!1;m.g.clientX=0;m.g.clientY=0;m.g.wheelDeltaX=0;m.g.wheelDeltaY=0;m.g.rotation=0;m.g.scale=1;m.g.changedTouches=null;m.g.preventDefault=(0,m.aa)(8);m.g.stopPropagation=(0,m.aa)(9);
var Od={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1};m.Qd=(0,m.q)("yt.events.listeners_")||{};(0,m.l)("yt.events.listeners_",m.Qd,void 0);var Rd=(0,m.q)("yt.events.counter_")||{count:0};(0,m.l)("yt.events.counter_",Rd,void 0);(0,m.fa)(Sd);Sd.prototype.getVersion=function(){return[this.b,this.g,this.j]};m.g=m.de.prototype;m.g.clone=function(){return new m.de(this.top,this.right,this.bottom,this.left)};m.g.contains=function(a){return(0,m.ee)(this,a)};m.g.ceil=(0,m.aa)(10);m.g.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};m.g.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
m.g.scale=function(a,b){var c=(0,m.ka)(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};var Ae=Bb("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));m.Kh=RegExp("^[^\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");m.Lh=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");m.je.prototype.qg=!0;m.je.prototype.pg=function(){return this.b};m.je.prototype.toString=function(){return"Const{"+this.b+"}"};var ke={};me.prototype.qg=!0;var ne={};me.prototype.pg=function(){return this.b};var ye=oe(""),xe=/^[-.%_!# a-zA-Z0-9]+$/;pe.prototype.qg=!0;pe.prototype.pg=function(){return""};pe.prototype.Ul=!0;pe.prototype.Hf=function(){return 1};var qe={};var se;var we;var ze;var ve;re.prototype.Ul=!0;re.prototype.Hf=function(){return this.g};re.prototype.qg=!0;re.prototype.pg=function(){return this.b};ve=/^[a-zA-Z0-9-]+$/;ze=Bb("action","cite","data","formaction","href","manifest","poster","src");we=Bb("link","script","style");se={};m.Mh=Ce("",0);m.Nh=(0,m.tb)(function(){if(m.G)return(0,m.Eb)("10.0");var a=window.document.createElement("div"),b=(0,m.ce)(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");b=(0,m.ue)("div",{style:c});a.innerHTML=(0,m.te)(b);a=a.firstChild;b=a.style[(0,m.Ia)("transition")];return""!=("undefined"!==typeof b?b:a.style[(0,m.fe)(a,"transition")]||"")});m.Fe={};(0,m.fa)(m.Ie);m.Je=(0,m.q)("yt.prefs.UserPrefs.prefs_")||{};(0,m.l)("yt.prefs.UserPrefs.prefs_",m.Je,void 0);m.g=m.Ie.prototype;m.g.get=function(a,b){Le(a);Ke(a);var c=void 0!==m.Je[a]?m.Je[a].toString():null;return null!=c?c:b?b:""};m.g.set=function(a,b){Le(a);Ke(a);if(null==b)throw"ExpectedNotNull";m.Je[a]=b.toString()};m.g.remove=function(a){Le(a);Ke(a);delete m.Je[a]};m.g.save=function(){var a;a=[];for(var b in m.Je)a.push(b+"="+(0,window.escape)(m.Je[b]));a=a.join("&");(0,m.xd)("PREF",a,63072E3)};
m.g.clear=function(){m.Je={}};var We=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var Ye;var Oh=m.Ld,Oh=Oh.toLowerCase();if((0,m.Ea)(Oh,"android")){var Ph=Oh.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(Ph)Ye=Number(Ph[1]);else{var Qh={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},Rh=Oh.match("("+(0,m.wb)(Qh).join("|")+")");Ye=Rh?Qh[Rh[0]]:0}}else Ye=void 0;(0,m.v)(m.$e,Ze);m.$e.prototype.ka=(0,m.aa)(1);m.$e.prototype.clear=function(){var a=(0,m.cc)(this.Ta(!0)),b=this;(0,m.A)(a,function(a){b.remove(a)})};(0,m.v)(m.af,m.$e);m.g=m.af.prototype;m.g.isAvailable=function(){if(!this.b)return!1;try{return this.b.setItem("__sak","1"),this.b.removeItem("__sak"),!0}catch(a){return!1}};m.g.set=function(a,b){try{this.b.setItem(a,b)}catch(c){if(0==this.b.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};m.g.get=function(a){a=this.b.getItem(a);if(!(0,m.r)(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};m.g.remove=function(a){this.b.removeItem(a)};
m.g.ka=(0,m.aa)(0);m.g.Ta=function(a){var b=0,c=this.b,d=new m.Zb;d.next=function(){if(b>=c.length)throw m.ac;var d;d=c.key(b++);if(a)return d;d=c.getItem(d);if(!(0,m.r)(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};m.g.clear=function(){this.b.clear()};m.g.key=function(a){return this.b.key(a)};(0,m.v)(m.bf,m.af);(0,m.v)(cf,m.af);var lf={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},kf=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;mf.prototype.set=function(a,b){(0,m.ca)(b)?this.b.set(a,(0,m.ef)(b)):this.b.remove(a)};mf.prototype.get=function(a){var b;try{b=this.b.get(a)}catch(c){return}if(null!==b)try{return(0,m.df)(b)}catch(d){throw"Storage: Invalid value was encountered";}};mf.prototype.remove=function(a){this.b.remove(a)};(0,m.v)(nf,mf);nf.prototype.set=function(a,b){nf.H.set.call(this,a,pf(b))};nf.prototype.Td=function(a){a=nf.H.get.call(this,a);if(!(0,m.ca)(a)||a instanceof Object)return a;throw"Storage: Invalid value was encountered";};nf.prototype.get=function(a){return(a=this.Td(a))?(0,m.qf)(a):void 0};(0,m.v)(rf,nf);rf.prototype.set=function(a,b,c){if(b=pf(b)){if(c){if(c<(0,m.J)()){rf.prototype.remove.call(this,a);return}b.expiration=c}b.creation=(0,m.J)()}rf.H.set.call(this,a,b)};rf.prototype.Td=function(a,b){var c=rf.H.Td.call(this,a);if(c)if(!b&&(0,m.sf)(c))rf.prototype.remove.call(this,a);else return c};(0,m.v)(m.tf,rf);m.tf.prototype.g=(0,m.aa)(11);var Th;var Sh;Sh=new m.bf;m.vf=Sh.isAvailable()?new m.tf(Sh):null;Th=new cf;m.wf=Th.isAvailable()?new m.tf(Th):null;(0,m.v)(zf,m.Ta);m.g=zf.prototype;m.g.getId=function(){return this.J};m.g.dh=function(a,b){this.ca()||(Bf(this,a),Hf(this,b),this.B&&Ef(this))};m.g.Mp=function(){return this.la};
m.g.Is=function(){if(!this.O){var a=!0;this.Da&&(a=If(this));a&&"html5"==Mf(this)?(this.A="html5",this.B||this.Fd(!0)):(Nf(this),this.A="html5",a&&this.ea?(this.Hc.appendChild(this.ea),this.Fd()):(this.T.loaded=!0,this.D=(0,m.s)(function(){var a=this.Hc,c=this.T.clone();(0,m.q)("yt.player.Application.create")(a,c);this.Fd()},this),this.O=!0,If(this)?this.D():((0,m.jd)(this.T.assets.js,this.D),(0,m.Ve)(this.T.assets.css))))}};
m.g.Hs=function(){var a=this.T.clone();a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==Mf(this)?(this.A="flash",this.B||Te(a,!1,(0,m.s)(this.Fd,this))):(Nf(this),this.A="flash",this.T.loaded=!0,(0,m.Pe)(this.Hc,a),this.Fd())};
m.g.Fd=function(a){var b=(0,m.H)(this.g),c=!1;try{b&&b.getApiInterface&&b.getApiInterface()&&(c=!0)}catch(d){}if(c)if(this.O=!1,a&&b.isNotServable&&b.isNotServable())Gf(this);else{Af(this);this.B=!0;a=(0,m.H)(this.g);a.addEventListener&&(this.F=Kf(this,a,"addEventListener"));a.removeEventListener&&(this.S=Kf(this,a,"removeEventListener"));b=a.getApiInterface();b=b.concat(a.getInternalApiInterface());for(c=0;c<b.length;c++){var e=b[c];this.b[e]||(this.b[e]=Kf(this,a,e))}for(var f in this.k)this.F(f,
this.k[f]);Ef(this);this.V&&this.V(this.b);this.N.U("onReady",this.b)}else this.Sa=(0,m.x)((0,m.s)(this.Fd,this),50)};m.g.Qp=function(){return this.B};m.g.yd=function(a,b){if(!this.ca()){var c=Df(this,b);if(c){if(!(0,m.Ma)(this.Xa,a)&&!this.k[a]){var d=Lf(this,a);this.F&&this.F(a,d)}this.N.subscribe(a,c);"onReady"==a&&this.B&&(0,m.x)((0,m.t)(c,this.b),0)}}};m.g.Pp=function(a,b){if(!this.ca()){var c=Df(this,b);c&&this.N.Rc(a,c)}};
m.g.tm=function(a){a=a?Wb:Vb;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||(b.focus(),b!=window.document.activeElement));)b=a(b)};m.g.vm=function(a){var b={};b.volume=(0,window.isNaN)(a.volume)?yf().volume:(0,m.ub)(a.volume,0,100);b.muted=void 0==a.muted?yf().muted:a.muted;(0,m.uf)("yt-player-volume",b,2592E3)};m.g.um=function(a){5==a&&Gf(this)};m.g.wm=function(a){(0,m.B)("WATCH_LATER_VIDEO_ADDED",a)};m.g.xm=function(a){(0,m.B)("WATCH_LATER_VIDEO_REMOVED",a)};
m.g.Js=function(){Nf(this);this.A="unsupported";var a=(0,m.hb)("PLAYER_FALLBACK",void 0,'The Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>'),b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a=(0,m.hb)("QUICKTIME_FALLBACK",void 0,'The Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>'));
b=(0,m.H)("player-unavailable");(0,m.H)("unavailable-submessage")&&b&&((0,m.H)("unavailable-submessage").innerHTML=a,(a=(0,m.I)("icon",b))&&(0,m.hd)(a,"icon")&&(a.src=(0,m.K)(a,"icon")),(0,m.F)(b,"hid"),(0,m.D)((0,m.H)("player"),"off-screen-trigger"))};m.g.Op=function(){return this.A||Mf(this)};m.g.Np=function(){return this.Fa};m.g.cancel=function(){this.D&&(0,m.ld)(this.T.assets.js,this.D);(0,m.y)(this.Sa);this.O=!1};
m.g.Dq=function(){var a=(0,m.q)("yt.player.ui.shared.init");a&&(this.b.hideUserInterface(),a(this.j,this.T.clone()))};m.g.K=function(){Nf(this);if(this.C){var a=(0,m.q)("yt.player.ui.shared.dispose");a&&a();this.ha=!1}this.da=null;for(var b in this.k)m.p[this.k[b]]=null;this.b=null;delete this.Hc;delete this.j;this.T&&(this.la=this.T=this.T.fallback=null);zf.H.K.call(this)};var Pf={};var Uh=(0,m.q)("yt.player.exports.navigate")||m.Gd;(0,m.l)("yt.player.exports.navigate",Uh,void 0);var Vh=(0,m.q)("yt.player.embed")||m.Of;(0,m.l)("yt.player.embed",Vh,void 0);var Wh=(0,m.q)("yt.player.destroy")||m.Sf;(0,m.l)("yt.player.destroy",Wh,void 0);var Xh=(0,m.q)("yt.player.cancelAll")||Rf;(0,m.l)("yt.player.cancelAll",Xh,void 0);var Yh=(0,m.q)("yt.player.getPlayerByElement")||m.Tf;(0,m.l)("yt.player.getPlayerByElement",Yh,void 0);var Zh=(0,m.q)("yt.player.exports.feedbackStart")||m.He;
(0,m.l)("yt.player.exports.feedbackStart",Zh,void 0);var Xf,cg=!1,bg="",Vf=!1;var hg=[];var ng,Fg,og=0,qg=[900,60,"waiting"],yg=[500,99,"waiting"],sg=[300,60,"waiting"],ug=[400,99,"waiting"],Ag=[300,101,"done"];var Hg=[];window.yt=window.yt||{};(0,m.l)("yt.setConfig",m.Ya,void 0);(0,m.l)("yt.getConfig",m.w,void 0);(0,m.l)("yt.hasMsg",m.gb,void 0);(0,m.l)("yt.pubsub.publish",m.B,void 0);(0,m.l)("yt.pubsub.subscribe",m.z,void 0);(0,m.l)("yt.setMsg",m.eb,void 0);(0,m.l)("yt.setGoogMsg",function(a){Za(m.fb,arguments)},void 0);(0,m.l)("yt.setAjaxToken",function(){},void 0);
(0,m.l)("reportTimingMaps",function(a,b,c,d){if(a)for(var e in a)(0,m.tc)(e,a[e],d);if(c)for(var f in c)wc(f,c[f],d);if(b)for(var h in b)a=h,c=b[h],xc(d).info[a]=c;return Gc(d)},void 0);(0,m.l)("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch7ad_html5":"watch7ad"};var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+a[e]);c.rt=d.join(",");for(var f in b)"_"!=f.charAt(0)&&(c[f]=b[f]);a=(0,m.w)("TIMING_INFO")||{};"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);zc(c)},void 0);
(0,m.v)(Jg,m.Mc);
Jg.prototype.enable=function(){window.onload=jg;window.onunload=kg;window.onerror=lg;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfrequested",mg),window.addEventListener("spfpartreceived",rg),window.addEventListener("spfpartprocessed",wg),window.addEventListener("spfreceived",xg),window.addEventListener("spfprocessed",zg),window.addEventListener("spferror",Bg),window.addEventListener("spfjsbeforeunload",Kg)),a.config=a.config||{},window.ytdepmap?window.spf.script.ready("spf",
function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",Cg),this.subscribe("dispose",Eg)):window.spf.dispose();this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
Jg.prototype.init=function(){Jg.H.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();Sc();var a,b;!window.ytPageFrameLoaded&&(0,m.w)("PAGEFRAME_JS")&&(a=(0,m.w)("PAGEFRAME_JS"),b=function(){(0,m.q)("ytbin.www.pageframe.setup")();window.ytPageFrameLoaded=!0});var c=(0,m.w)("JS_COMMON_MODULE"),d=(0,m.w)("JS_PAGE_MODULES");if(window.ytdepmap)d||(d=[c]),c=(0,m.w)("JS_DELAY_LOAD",void 0),0<c?((0,m.y)(this.b),this.b=(0,m.x)(function(){a&&(0,m.jd)(a,b);window.spf.script.require(d)},c)):(a&&
(0,m.jd)(a,b),window.spf.script.require(d));else{var e={};e[c]=d;c=(0,m.w)("JS_DELAY_LOAD",void 0);0<c?((0,m.y)(this.b),this.b=(0,m.x)(function(){a&&(0,m.jd)(a,b);(0,m.md)(e)},c)):(a&&(0,m.jd)(a,b),(0,m.md)(e))}Gg();Uf()};
Jg.prototype.dispose=function(){(0,m.y)(this.b);var a=(0,m.q)("ytbin.www.pageframe.cancelSetup");a&&a();(0,m.M)(Hg);Hg.length=0;(0,m.cb)(Xf);if(a=(0,m.Zf)())a.removeEventListener("onReady",Yf),a.removeEventListener("onStateChange",Yf),a.removeEventListener("onReady",$f),a.removeEventListener("onStateChange",$f);Jg.H.dispose.call(this)};
Jg.prototype.disable=function(){Jg.H.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfrequested",mg),window.removeEventListener("spfpartreceived",rg),window.removeEventListener("spfpartprocessed",wg),window.removeEventListener("spfreceived",xg),window.removeEventListener("spfprocessed",zg),window.removeEventListener("spferror",Bg),window.removeEventListener("spfjsbeforeunload",Kg));window.onload=null;window.onunload=null;window.onerror=null};(0,m.Oc)(new Jg);})(_yt_www);
