(function(m){var window=this;var MI=function(a){if(!a.length)return 0;var b=a[0],c=b.offsetHeight;1<a.length&&(c=a[1].offsetTop-b.offsetTop);return c};var NI=function(){var a=m.Qr.getInstance(),b=OI;if(!b)return[];a=(0,m.P)((0,m.V)(a,"scroll-unit"),b);if(0>=a.length)return[];var c=b.scrollTop,d=MI(a),e=b.offsetHeight,b=Math.max(Math.floor(c/d),0),c=Math.min(Math.ceil((c+e)/d),a.length);return(0,m.Sa)((0,m.Ra)(a),b,c)};
var PI=function(a,b){var c=(0,m.H)(b);if(c){var d=(0,m.V)(a,"toggled"),c=(0,m.P)(d,c);(0,m.A)(c,function(a){(0,m.F)(a,d)})}};var QI=function(a){(0,m.l)("yt.net.apiloader.onApiLoaded_GOOGLE_JSAPI",a,void 0)};var RI=function(){var a=(0,m.P)("related-video-featured");(0,m.A)(a,function(a){(0,m.N)(a)})};
var SI=function(a,b,c){var d={};0===b?d.action_like_video=1:1===b?d.action_dislike_video=1:d.action_indifferent_video=1;d.video_id=a;d.plid=c.Er;c.Gh&&(d.list=c.Gh);c.Kh&&(d.authuser=c.Kh);c.Lh&&(d.pageid=c.Lh);a={screen:(0,m.nc)({h:window.screen.height,w:window.screen.width,d:window.screen.colorDepth}),session_token:(0,m.T)()};c.zk&&(a.station_id=c.zk);(0,m.U)("/watch_actions_ajax",{format:"XML",method:"POST",W:d,P:a,onSuccess:c.onSuccess,onError:c.onError,aa:c.aa})};
var TI=function(a,b,c,d){if((0,m.T)())c&&window.setTimeout(c,0);else{var e=(0,m.sl)(window.document.location.href)+"/token_ajax",f={};a&&(f.authuser=a);b&&(f.pageid=b);f[UI.watch_actions_ajax]=1;(0,m.U)(e,{format:"RAW",method:"GET",W:f,aa:function(a){var b=(0,m.Qi)(a.responseText);b[VI.watch_actions_ajax]?c&&c():d&&d(a,b)}})}};var WI=function(a,b){var c=(0,m.w)("I18N_PLURAL_RULES")||function(a){return 1==a?"one":"other"};return(c=a["case"+b]||a[c(b)])?c.replace("#",b.toString()):b+""};
var XI=function(a){return(0,m.U)("/insight_ajax",{format:"XML",method:"POST",W:{action_get_statistics_and_data:1,v:(0,m.w)("VIDEO_ID")},P:{session_token:(0,m.T)()},onSuccess:function(b,c){a(c.html_content,c.graph_data,!0)},onError:function(){a(null,null,!1)}})};
var YI=function(a){var b=0,c=(0,m.KG)();c&&c.pauseVideo&&(c.pauseVideo(),b=c.getCurrentTime());b=Math.floor(b);c=Math.floor(b/60);return(0,m.U)("/watch_ajax",{method:"GET",W:{action_get_report_video_component:1,video_id:(0,m.w)("VIDEO_ID"),t_mins:c,t_secs:b-60*c},onSuccess:function(b,c){a(c.report_html,!0)},onError:function(){a(null,!1)}})};
var ZI=function(a){var b=window.location.href;b.indexOf("#")==b.length-1&&m.$d&&(window.location.hash="#!");var b=window.document.body,c=(0,m.Ci)(b),d=[];d.push("<!DOCTYPE html>");d.push("<html><head>",a,"</head><body>","","</body></html>");a=(0,m.VD)(c,"display: none");b.appendChild(a);b=d.join("");d=a.contentDocument||a.contentWindow.document;d.open();d.write(b);d.close();m.DE=a};
var $I=function(){var a=(0,m.P)("related-video-featured");2==a.length?(0,m.C)(a[0],"related-video-featured-booster")?(0,m.N)(a[1]):(0,m.N)(a[0]):(0,m.A)(a,function(a){(0,m.N)(a)})};
var aJ=function(a){0==a.length?RI():(0,m.EE)("watch_related",a[0],null,function(a,c){var d=c.html_content||"",e=(0,m.H)(window.pyv_related_box_id||"watch-related");e&&(0!=e.innerHTML.indexOf(d)&&e.insertBefore((0,m.xj)(d),e.firstChild),(d=(0,m.H)("pyv-watch-related-dest-url"))&&d.setAttribute("href",m.FE),d=m.HE,(0,m.pc)(d,void 0,(0,m.ml)(d)))})};var bJ=function(a,b,c){c=c||{};TI(c.Kh,c.Lh,(0,m.s)(SI,m.p,a,b,c),c.onError)};
m.cJ=function(a,b){var c=a.type;if((0,m.ca)(c))switch(c.toLowerCase()){case "checkbox":case "radio":a.checked=b?"checked":null;break;case "select-one":a.selectedIndex=-1;if((0,m.r)(b))for(var d=0;c=a.options[d];d++)if(c.value==b){c.selected=!0;break}break;case "select-multiple":c=b;(0,m.r)(c)&&(c=[c]);for(var e=0;d=a.options[e];e++)if(d.selected=!1,c)for(var f,h=0;f=c[h];h++)d.value==f&&(d.selected=!0);break;default:a.value=null!=b?b:""}};var dJ=function(a){a=(0,m.kd)(a);window.spf.script.unload(a)};
var eJ=function(a,b){return WI(a in m.fb?m.fb[a]:{},b)};var fJ=function(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var d=[],e=0;e<arguments.length;e++){var f=arguments[e];if(c>=f.length)return b;d.push(f[c])}b.push(d)}};var gJ=function(){this.b=new m.zE(this);this.j=!1};
var hJ=function(){if((0,m.w)("WATCH_LEGAL_TEXT_ENABLE_AUTOSCROLL")){var a=window.document.getElementById("watch_companion_legal_text");a&&(iJ=new gJ,iJ.start(a))}var b=(0,m.w)("ADS_DATA");if(b){jJ(b);kJ=b;lJ=(0,m.KG)();null!=lJ&&(lJ.addEventListener("onApiChange",mJ),lJ.addEventListener("onReady",nJ));b.show_pyv?oJ(b):RI();b.use_gut&&(dJ("//www.googletagservices.com/tag/js/gpt.js"),(0,m.jd)("//www.googletagservices.com/tag/js/gpt.js",function(){if("googletag"in window&&(pJ=window.googletag.defineSlot(b.gut_vars.tag,
[[300,250],[300,60]],"google_companion_ad_div"))){pJ.set("ad_type","flash");pJ.addService(window.googletag.companionAds());window.googletag.enableServices();var a=pJ.getSizes();qJ=a[0];rJ=a[1]}}));if(b.show_afv||b.show_afc)dJ("//pagead2.googlesyndication.com/pagead/show_companion_ad.js"),(0,m.jd)("//pagead2.googlesyndication.com/pagead/show_companion_ad.js",sJ),(0,m.jd)("//www.google.com/jsapi?autoload=%7B%22modules%22%3A%5B%7B%22name%22%3A%22ads%22%2C%22version%22%3A%221%22%2C%22callback%22%3A%22(function()%7B%7D)%22%2C%22packages%22%3A%5B%22content%22%5D%7D%5D%7D");
b.show_afc&&tJ(b);uJ();b.check_status&&vJ();(0,m.B)("adJavaScriptInitialized")}};var vJ=function(){function a(){wJ=!0;"google_ad_status"in window?(0,m.mm)("adstat=s"):(0,m.mm)("adstat=l")}(0,m.jd)("//static.doubleclick.net/instream/ad_status.js",a);(0,m.x)(function(){wJ||"google_ad_status"in window||((0,m.ld)("//static.doubleclick.net/instream/ad_status.js",a),(0,m.mm)("adstat=f"))},5E3)};
var uJ=function(){var a;if(a=xJ&&null!=lJ&&null!=lJ.getOptions)a=null!=lJ.getOptions();a&&(0,m.Ma)(lJ.getOptions(),"ad")&&lJ.getOption("ad","PAGE_JAVASCRIPT_INITIALIZED",{})};var jJ=function(a){yJ=[];if("afv_vars"in a)for(var b in a.afv_vars)window[b]=a.afv_vars[b],yJ.push(b)};var zJ=function(a,b){a||(a="");b||(b=!1);var c=(0,m.H)("watch-channel-brand-div");c&&(0,m.sb)(c,"collapsible",b);if(c=(0,m.H)("google_companion_ad_div"))c.innerHTML=a};
var AJ=function(a){var b=Math.round(1E4*Math.random());return['<iframe src="',a,'" name="ifr_300x250ad',b,'" id="ifr_300x250ad',b,'" width="300" height="250" marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>'].join("")};var BJ=function(){var a=(0,m.H)("watch7-sidebar-ads");a&&(0,m.D)(a,"ad-loaded")};var CJ=function(a){return!!a.match("/ad_companion.*render=video_wall_companion")};
var DJ=function(a,b){var c=250;"video"==a&&(c=60);var d=(0,window.decodeURIComponent)(b);zJ(['<iframe name="fw_ad" id="fw_ad" ','width="300" height="'+c+'" ','marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>'].join(""));var e=(0,m.H)("fw_ad");if(e){var e=e.contentWindow?e.contentWindow:e.contentDocument.document?e.contentDocument.document:e.contentDocument,f=window.navigator.userAgent.toLowerCase(),c=-1!=f.indexOf("msie"),f=-1!=f.indexOf("opera");e.document.open();
e.document.write(d);c||f?(0,m.x)(function(){e.document.close()},7500):e.document.close()}};var sJ=function(){(0,m.B)("showCompanionAdLoaded")};var EJ=function(){window.google_ad_output="html";window.google_ad_height="250";window.google_ad_format="300x250_as";window.google_container_id="google_companion_ad_div"};
var FJ=function(){var a=window.document.getElementById("google_companion_ad_div");if(a&&(a=a.firstElementChild)){"DIV"==a.nodeName&&(a=a.firstElementChild);try{a.contentWindow.postMessage((0,window.encodeURIComponent)(GJ)+","+(0,window.encodeURIComponent)(HJ),"*"),a.width=370,a.height=null!=GJ?210:185}catch(b){}}};var IJ=function(){var a=window.document.getElementById("movie_player");a&&a.pauseVideo()};
var oJ=function(a){ZI("<script>var pyvOptions = "+a.pyv_vars.iframe_json+'; for (var key in pyvOptions) { window[key] = pyvOptions[key]; } window["google_ad_request_done"] = parent.yt.www.ads.pyv.pyvWatchAfcWithPpvCallback; \x3c/script><script src="//pagead2.googlesyndication.com/pagead/show_ads.js">\x3c/script>');BJ();a.log_pyv&&(0,m.x)(function(){"google_render_ad"in window?(0,m.mm)("pyvls"):(0,m.mm)("pyvlf")},5E3)};
var tJ=function(a){if(!JJ){if(!a){if(!kJ)return;a=kJ}var b=(0,m.q)("google.ads.Ad");b?(JJ=!0,new b(a.afv_vars.google_ad_client,"google_companion_ad_div",a.afc_vars)):KJ=(0,m.x)(function(){tJ(a)},200);BJ()}};var mJ=function(){uJ()};var nJ=function(){xJ=!0;uJ()};var LJ=function(){var a=(0,m.w)("BG_I",null),b=(0,m.w)("BG_IU",null),c=(0,m.w)("BG_P");b?(0,m.jd)(b,function(){MJ=new window.botguard.bg(c)}):a&&(eval(a),MJ=new window.botguard.bg(c))};
var NJ=function(){return!OJ&&(OJ=!0,(0,m.w)("BG_P")&&((0,m.w)("BG_I")||(0,m.w)("BG_IU")))?(LJ(),!0):!1};var PJ=function(){var a=(0,m.yr)();(0,m.S)((0,m.I)("flag-comment-step1",a));(0,m.N)((0,m.I)("flag-comment-step2",a));(0,m.S)((0,m.I)("flag-comment-step3",a))};
var QJ=function(){var a=(0,m.yr)(),b=(0,m.I)("flag-comment-form",a),c=(0,m.I)("flag-comment-block-user-input",a),d=(0,m.I)("submit-flag-comment",a),e=(0,m.I)("flag-comment-error-msg",a);(0,m.S)(e);c.disabled=!0;d.disabled=!0;(0,m.U)("/comment_servlet",{format:"XML",method:"POST",W:{flag_comment:1},P:(0,m.Qi)((0,m.Im)(b)),onSuccess:function(b,c){c&&c.html_content?((0,m.S)((0,m.I)("flag-comment-step1",a)),(0,m.S)((0,m.I)("flag-comment-step2",a)),(0,m.N)((0,m.I)("flag-comment-step3",a)),(0,m.I)("flag-comment-captcha-placeholder",
a).innerHTML=c.html_content):m.tr.getInstance().hide()},onError:function(a,b){var k=b&&b.error_message;if(k){var n=(0,m.I)("yt-alert-message",e);(0,m.zl)(n,k)}(0,m.N)(e);c.disabled=!1;d.disabled=!1}})};var RJ=function(a){var b=(0,m.yr)(),c=(0,m.I)("abuse-type-placeholder",b);a=(0,m.li)(a.currentTarget,"LABEL");(0,m.zl)(c,(0,m.xl)(a));(0,m.I)("continue-flag-comment",b).disabled=!1};
var SJ=function(a,b,c){this.D=!!c;this.na=a;this.yi=(0,m.H)("all-comments");this.kc=(0,m.Pj)("button","post-button",a);this.gb=(0,m.Pj)("textarea",null,a);this.Nc=null;this.b=(0,m.I)("comments-remaining",this.na);this.B=(0,window.parseInt)((0,m.K)(this.b,"max-count"),10);this.Kc=(0,m.I)("comments-post-message",this.na);this.xi=(0,m.I)("yt-alert-content",this.Kc);this.g=(0,m.I)("comments-threshold-countdown",this.na);this.A=[];this.k=[];this.j=null;this.nn=!!(0,m.w)("COMMENTS_IS_LIVE_EVENT");TJ(this);
UJ(this,this.gb,"focus",this.Ei);UJ(this,this.gb,"blur",this.qn);UJ(this,this.na,"submit",this.Ci);UJ(this,this.gb,"change",this.Di);UJ(this,this.gb,"keyup",this.Di);UJ(this,this.gb,"keydown",this.rn);b&&this.Ei()};
var VJ=function(a){var b;switch(a){case "PENDING":b=(0,m.hb)("COMMENT_PENDING");break;case "BLOCKED":b=(0,m.hb)("COMMENT_BLOCKED");break;case "EMAIL":b=(0,m.hb)("COMMENT_ERROR_EMAIL");break;case "INLINE_CAPTCHAFAIL":b=(0,m.hb)("COMMENT_CAPTCHAFAIL");break;case "SHOW_COUNTDOWN":b=(0,m.hb)("SHOW_COUNTDOWN");break;case "FAILED_MAINTENANCE":b=(0,m.hb)("COMMENT_FAILED_MAINTENANCE");break;case "FAILED_OWNER_LINKING":b=(0,m.hb)("COMMENT_OWNER_LINKING");break;case "FAILED_HASLINK":b=(0,m.hb)("FAILED_HASLINK");
break;case "FAILED_HASTAGS":b=(0,m.hb)("FAILED_HASTAGS");break;case "FAILED_ASCIIART":b=(0,m.hb)("FAILED_ASCIIART");break;case "FAILED_TOOSHORT":b=(0,m.hb)("FAILED_TOOSHORT");break;case "FAILED_TOOLONG":b=(0,m.hb)("FAILED_TOOLONG");break;case "FAILED_BADPARENT":b=(0,m.hb)("FAILED_BADPARENT")}return b||(0,m.hb)("COMMENT_ERROR")};var WJ=function(a){XJ(a);YJ(a);(0,m.zj)(a.na,"has-focus");a.kc.disabled=!1;a.gb.value="";TJ(a);a.gb.blur();a.j=null;a.destroy();(0,m.B)("comment-form-reset")};
var UJ=function(a,b,c,d){a.A.push((0,m.L)(b,c,(0,m.s)(d,a)))};var XJ=function(a){a.Nc&&(a.Nc.innerHTML="")};var TJ=function(a){var b=a.B-a.gb.value.length;a.b.innerHTML=eJ("CHARACTERS_REMAINING",b);b=0>b;(0,m.nk)(a.b,"too-many",b);a.kc.disabled=b};var ZJ=function(a,b){var c=(0,m.s)(function(){0==b?((0,m.cb)(d),YJ(this)):(b--,this.g.innerHTML=eJ("SECONDS_REMAINING",b))},a);$J(a);var d=(0,m.bb)(c,1E3);c();a.k.push(d)};var $J=function(a){(0,m.S)(a.b);(0,m.N)(a.g);a.kc.disabled=!0};
var YJ=function(a){(0,m.S)(a.g);(0,m.S)(a.Kc);(0,m.N)(a.b);a.g.innerHTML="";a.kc.disabled=!1};
var aK=function(a,b,c){var d=VJ(b);a.xi.innerHTML=d;(0,m.Jl)(a.Kc,"yt-alert-info","yt-alert-error");(0,m.N)(a.Kc);switch(b){case "INLINE_CAPTCHA":case "INLINE_CAPTCHAFAIL":(0,m.U)("/comment_servlet?gimme_captcha=1",{format:"XML",method:"POST",P:{session_token:(0,m.T)()},onSuccess:function(a,b){this.Nc||(this.Nc=window.document.createElement("div"),this.Nc.className="comment-captcha",(0,m.Fl)(this.Nc,this.gb));this.Nc.innerHTML=b.html_content;this.kc.disabled=!1},context:a});break;case "SHOW_COUNTDOWN":ZJ(a,
(0,window.parseInt)(c.countdown_timer,10)||30);break;default:a.kc.disabled=!1,XJ(a)}};var bK=function(a){this.$=a;this.Xi=(0,m.I)("yt-uix-pager-show-more");this.j=!!(0,m.w)("ENABLE_LIVE_COMMENTS");this.b=[];(a=(0,m.I)("comments-pagination",this.$))&&(0,m.K)(a,"ajax-enabled")&&this.b.push((0,m.R)(this.$,"click",(0,m.s)(this.k,this),"yt-uix-pager-button"))};
var cK=function(a,b){var c=(0,m.Kb)("li","comment",void 0),c=(0,m.K)(c[c.length-1],"id"),d=a.Le?!1:!0;(0,m.N)("comments-loading");dK(a,c,function(a,c){c.html_content&&((0,m.S)("comments-loading"),this.Le=window.document.createElement("div"),this.Le.innerHTML=c.html_content,!d&&0<(0,m.Kb)("li","comment",this.Le).length&&(0,m.N)(this.Xi),b&&b())})};
var dK=function(a,b,c){(0,m.U)("/watch_ajax?action_get_comments=1",{format:"XML",W:{v:(0,m.w)("VIDEO_ID"),p:1,commentthreshold:(0,m.w)("COMMENTS_THRESHHOLD"),commenttype:"everything",enable_live_comments:a.j?"yes":null,last_comment_id:b,page_size:(0,m.w)("COMMENTS_PAGE_SIZE"),source:(0,m.w)("COMMENT_SOURCE")},onSuccess:c,context:a})};var eK=function(a,b,c){a=(0,m.li)(a,"form");(0,m.hd)(a,"initialized")||((0,m.kl)(a,"initialized","true"),fK=new SJ(a,!b,c),b&&fK.focus())};
var gK=function(a){a=a.currentTarget;var b=(0,m.li)(a,null,"comment");switch((0,m.K)(a,"action")){case "approve":hK(b);break;case "block":(0,window.confirm)((0,m.hb)("BLOCK_USER"))&&(iK(b,!0),(0,m.Aj)(b,"blocked"));break;case "unblock":iK(b,!1);(0,m.zj)(b,"blocked");break;case "flag-in-place":if(jK(!1)){var c=(0,m.H)("comment-flag-area");a=(0,m.K)(b,"id");var d=(0,m.K)(b,"author-id"),e=(0,m.xl)((0,m.I)("author",b)),b=(0,m.I)("comment-text",b).innerHTML,f=(0,m.w)("VIDEO_ID");m.tr.getInstance().show(c);
c=(0,m.yr)();(0,m.I)("flagged-comment-id",c).value=a;(0,m.I)("flagged-comment-author-id",c).value=d;(0,m.I)("flagged-comment-video-id",c).value=f;(0,m.zl)((0,m.I)("flagged-comment-author-name",c),e);(0,m.I)("flagged-comment-text",c).appendChild((0,m.xj)(b));(0,m.L)((0,m.I)("continue-flag-comment",c),"click",PJ);(0,m.R)(c,"click",QJ,"submit-flag-comment");(0,m.R)(c,"click",RJ,"abuse-type-radio-input")}break;case "flag":kK(b,"mark_comment_as_spam");break;case "flag-profile-pic":kK(b,"flag_profile_pic");
break;case "unflag":a=(0,m.K)(b,"id");(0,m.U)("/comment_servlet",{format:"XML",method:"POST",P:{unmark_comment_as_spam:a,entity_id:(0,m.w)("VIDEO_ID"),session_token:(0,m.T)()}});break;case "hide":(0,m.Aj)(b,"hidden");break;case "show":(0,m.zj)(b,"hidden");break;case "remove":lK(b);break;case "reply":mK(b);break;case "realtime-reply":jK(!0)&&(fK||(a=(0,m.I)("comments-textarea",(0,m.H)("comments-view")),eK(a)),a=fK,WJ(a),a.focus());break;case "vote-up":nK(b,!0);break;case "vote-down":nK(b,!1);break;
case "show-parent":oK(b)}};var jK=function(a){return(0,m.w)("COMMENTS_SIGNIN_URL")?((0,m.Ed)((0,m.w)("COMMENTS_SIGNIN_URL")),!1):a&&(0,m.w)("COMMENTS_CHANNEL_CREATE_URL")?((0,m.Ed)((0,m.w)("COMMENTS_CHANNEL_CREATE_URL")),!1):(0,m.w)("COMMENTS_YPC_CAN_POST_OR_REACT_TO_COMMENT")?!0:!1};
var hK=function(a){var b=(0,m.K)(a,"id"),c=(0,m.w)("VIDEO_ID");(0,m.zj)(a,"pending");(0,m.U)("/comment_servlet?field_approve_comment=1",{format:"XML",method:"POST",P:{comment_id:b,entity_id:c,session_token:(0,m.T)()},onError:function(){(0,m.Aj)(a,"pending")}})};
var iK=function(a,b){var c={};c["action_"+(b?"":"un")+"block_commenter"]=1;var d=(0,m.K)(a,"id");(0,m.U)("/link_ajax",{format:"XML",method:"POST",W:c,P:{session_token:(0,m.T)(),comment_id:d},onSuccess:function(a,b){b&&b.success_message&&window.alert(b.success_message)},onError:function(a,b){b&&b.error_message&&window.alert(b.error_message)}})};
var kK=function(a,b){if(jK(!1)){var c=(0,m.K)(a,"id"),d=(0,m.w)("VIDEO_ID");(0,m.S)(a);(0,m.Aj)(a,"flagged");d={entity_id:d};d[b]=c;(0,m.U)("/comment_servlet",{format:"XML",method:"POST",W:d,P:{session_token:(0,m.T)()},onError:function(){(0,m.N)(a);(0,m.zj)(a,"flagged")}})}};var lK=function(a){var b=(0,m.K)(a,"id"),c=(0,m.w)("VIDEO_ID");(0,m.S)(a);(0,m.U)("/comment_servlet?remove_comment=1",{format:"XML",method:"POST",P:{comment_id:b,entity_id:c,session_token:(0,m.T)()},onError:function(){(0,m.N)(a)}})};
var mK=function(a){if(jK(!0))if((0,m.ok)(a,"replying"))(0,m.ok)(a,"replying")&&((0,m.zj)(a,"replying"),a=(0,m.I)("comments-post-container",a),(0,m.Ub)(a));else{(0,m.Aj)(a,"replying");var b=(0,m.I)("comments-post",(0,m.H)("watch-discussion")||(0,m.H)("watch-discussion")),b=(0,m.cl)(b),c=window.document.createElement("div");c.className="comments-post-container";a.appendChild(c);c.appendChild(b);b=new SJ(b);WJ(b);c=(0,m.K)(a,"id");b.na.reply_parent_id.value=c;if(a=(0,m.K)(a,"tag"))b.j=a;b.focus()}};
var nK=function(a,b){if(jK(!1)&&!(0,m.K)(a,"voted")){var c=(0,m.K)(a,"id"),d=(0,m.w)("VIDEO_ID"),e=(0,m.K)(a,"score")||"0",f=b?1:-1;(0,m.kl)(a,"voted",f+"");b?(0,m.Jl)(a,"voted-down","voted-up"):(0,m.Jl)(a,"voted-up","voted-down");c={a:f,id:c,video_id:d,old_vote:e};(d=(0,m.K)(a,"tag"))&&(c.tag=d);(0,m.U)("/comment_voting",{format:"XML",method:"POST",W:c,P:{session_token:(0,m.T)()}})}};
var oK=function(a){var b=(0,m.K)(a,"id"),c=(0,m.w)("VIDEO_ID");(0,m.zj)(a,"has-child");(0,m.Aj)(a,"child");var d=(0,m.H)("parent-comment-loading");if(d){var e=(0,m.cl)(d);(0,m.ri)(e,a);(0,m.N)(e)}(0,m.U)("/comment_servlet?get_comment_parent=1",{format:"XML",method:"POST",P:{comment_id:b,entity_id:c,session_token:(0,m.T)()},onSuccess:function(b,c){var d=window.document.createElement("ul");d.innerHTML=c.html_content;d=(0,m.mk)(d);(0,m.ri)(d,a);(0,m.Ub)(e);(0,m.Oq)(d)},onError:function(b,c){(0,m.Aj)(a,
"has-child");(0,m.zj)(a,"child");(0,m.Ub)(e);c&&c.error_message?window.alert(c.error_message):window.alert("Request failed, please try later.")}})};var pK=function(){if(-2==qK){qK=(0,window.parseInt)((0,m.zd)("ACTIVITY","-1"),10);(0,m.L)(window.document,"keypress",rK);(0,m.L)(window.document,"click",sK);var a=(0,m.w)("LIST_AUTO_PLAY_VALUE");a&&1<a||tK()}};var rK=function(){tK()};var sK=function(){tK()};var tK=function(){pK();var a=(0,m.J)();1E3>a-qK||(qK=a,(0,m.xd)("ACTIVITY",""+a))};
var uK=function(){return-1==qK||-2==qK?-1:Math.max((0,m.J)()-qK,0)};var vK=function(){return(0,m.C)((0,m.H)("page-container"),"remote-connected")};var wK=function(){var a=(0,m.H)("watch-queue-mole");return!!a&&(0,m.cj)(a)};var xK=function(){if(!yK){var a=(0,m.H)("watch-queue");if(!a)return[];yK=(0,m.I)("watch-queue-items-list",a)}var b=[],a=(0,m.qi)(yK);(0,m.A)(a,function(a){(a=(0,m.K)(a,"video-id"))&&b.push(a)});return b};
var zK=function(a){if(!a.metaKey&&!a.ctrlKey){var b=a.target;if("INPUT"!=b.tagName&&"TEXTAREA"!=b.tagName&&"SELECT"!=b.tagName&&"EMBED"!=b.tagName)switch(a.keyCode){case 78:a.shiftKey&&(0,m.B)("player-shortcut-next");break;case 80:a.shiftKey&&(0,m.B)("player-shortcut-prev");break;case 106:(0,m.B)("player-shortcut-rewind");break;case 108:(0,m.B)("player-shortcut-fast-forward");break;case 107:(0,m.B)("player-shortcut-play-pause")}}};
var AK=function(){BK=(0,m.H)("watch-appbar-playlist");OI=(0,m.I)("playlist-videos-list",BK);CK=(0,m.I)("toggle-autoplay",BK);DK=(0,m.I)("shuffle-playlist",BK);EK=(0,m.I)("next-playlist-list-item",BK);FK=(0,m.I)("prev-playlist-list-item",BK);GK=(0,m.I)("playlist-header-content",BK);HK="currently-playing";if(BK&&OI){var a=(0,m.KG)();a&&(IK=a,a.addEventListener("onReady",JK));GK&&(KK="true"===(0,m.K)(GK,"initial-autoplay-state"));LK.push((0,m.L)(CK,"click",MK));LK.push((0,m.L)(DK,"click",NK));LK.push((0,m.L)(EK,
"click",function(a){OK(a,"bf_next")}));LK.push((0,m.L)(FK,"click",function(a){OK(a,"bf_prev")}));LK.push((0,m.Uk)(OI,PK,"a"));LK.push((0,m.R)(OI,"click",QK,"yt-uix-button-playlist-remove-item"));RK.push((0,m.z)("navigate",SK));RK.push((0,m.z)("player-state-change",TK));RK.push((0,m.z)("player-error",UK));RK.push((0,m.z)("player-shortcut-next",VK));RK.push((0,m.z)("player-shortcut-prev",WK));RK.push((0,m.z)("watch-queue-show",function(a){vK()&&(0==a?(0,m.D)(BK,"watch-queue-nav"):(0,m.S)(BK))}));RK.push((0,m.z)("watch-queue-hide",
function(){(0,m.N)(BK);(0,m.F)(BK,"watch-queue-nav")}));vK()&&wK()&&(0==((0,m.mk)((0,m.H)("watch-queue-mole"))?0:1)?(0,m.D)(BK,"watch-queue-nav"):(0,m.S)(BK));(0,m.w)("SKIP_TO_NEXT_VIDEO")&&XK(5);YK();ZK();$K()}};var aL=function(a,b){var c;if(b){if(!KK||bL)return;var d=GK;d&&(c=(0,m.K)(d,"autoplay-clicktracking")||"")}d=EK;cL(d.href,a||"bf_next",c,b);(0,m.Fd)(d.href)};var ZK=function(){var a=NI();(0,m.A)(a,function(a){(0,m.Wq)(a)})};
var JK=function(a){IK.removeEventListener("onReady",JK);IK=a;a.addEventListener("onCueRangeEnter",dL);var b=(0,m.w)("LIST_END_TIME");b||(b=a.getDuration());if((0,m.w)("PREFETCH_NEXT_PLAYLIST_VIDEO")&&(0,m.w)("PREFETCH_NEXT_PLAYLIST_VIDEO_TIME")){var c=(0,m.w)("PREFETCH_NEXT_PLAYLIST_VIDEO_TIME");a.addCueRange("AUTOPLAY_PREFETCH",b-c,b-c+1)}};var dL=function(a){if("AUTOPLAY_PREFETCH"==a&&KK&&!bL){a=GK;var b;a&&(b=(0,m.K)(a,"autoplay-clicktracking")||"");a=EK.href;cL(a,"autoplay",b,!0);(0,m.HD)(a)}};
var $K=function(){(0,m.Hc)()?((0,m.Kc)(eL),eL=(0,m.Jc)((0,m.t)(m.ob,"watch-list-change"),void 0)):(0,m.B)("watch-list-change")};var XK=function(a,b){var c=b||"mr_meh";fL?gL=(0,m.x)(function(){XK(a,c)},1E3):(hL(a),0==a?aL(c,!0):gL=(0,m.x)(function(){XK(a-1,c)},1E3))};var iL=function(){var a=GK;return!(!a||"False"==(0,m.K)(a,"shareable"))};var MK=function(){var a=(0,m.so)(m.$n.getInstance(),CK);(0,m.Ya)("LIST_AUTO_PLAY_ON",!a);KK=!a};
var NK=function(){var a=OI,b=(0,m.Ra)(a.getElementsByTagName("li"));if((0,m.so)(m.$n.getInstance(),DK))b=jL(b),(0,m.Ya)("SHUFFLE_VALUE",0);else var c=kL(b),b=lL(b,c);(0,m.Tb)(a);(0,m.A)(b,function(b){a.appendChild(b)});c=(0,m.w)("SHUFFLE_VALUE");mL(b,c);YK();ZK();$K()};var PK=function(a){var b=(0,m.li)(a.currentTarget,"li"),b=(0,m.K)(b,"clicktracking")||"";nL(a,void 0,b)};var OK=function(a,b){var c=(0,m.K)(a.currentTarget,"clicktracking")||"";nL(a,b,c)};
var nL=function(a,b,c){var d=a.currentTarget.href;b=b||"BFa";var e={},f=(0,m.w)("SHUFFLE_VALUE");f?e.shuffle=f:-1!=d.indexOf("shuffle=")&&(e.shuffle=0);e&&(d=(0,m.fl)(d,e));a.currentTarget.href=d;cL(d,b,c)};
var QK=function(a){var b=GK,c=(0,m.li)(a.currentTarget,"li");if(b&&c){var d=OI;(0,m.D)(d,"playlist-editing-locked");a=(0,m.K)(b,"full-list-id");b=(0,m.K)(c,"video-id");(0,m.Gs)({ja:b,ed:a,onSuccess:function(){(0,m.Ub)(c);var a=(0,m.Kb)("li",null,d),b=1;(0,m.A)(a,function(a){(0,m.kl)(a,"index",b);b+=1});var h=(0,m.I)("currently-playing",d),h=h&&(0,m.K)(h,"index")||0;(0,m.H)("playlist-current-index").innerHTML=h;(0,m.H)("playlist-length").innerHTML=b-1;mL(a,(0,m.w)("SHUFFLE_VALUE"))},aa:function(){(0,m.F)(d,
"playlist-editing-locked");$K()}})}};var TK=function(a){0==a&&((0,m.Yk)()||aL("autoplay",!0))};var UK=function(){};var VK=function(){aL("keys")};var WK=function(){var a=FK;cL(a.href,"keys");(0,m.Fd)(a.href)};var SK=function(){bL=!0};
var lL=function(a,b){function c(a){var c=0,d=[];for(a=a.split("");a.length;){var c=(b+c)%a.length,e=a[c];(0,m.Pa)(a,c);d.push(e)}return d.join("")}(0,m.Zl)(a,function(a,b){var d=(0,m.K)(a,"video-id"),e=(0,m.K)(b,"video-id");return c(d).localeCompare(c(e))});var d=b>>8,e=(0,m.La)(a,function(a){a=(0,m.K)(a,"index");return d==a})||0;0<e&&(a=(0,m.Sa)(a,e).concat((0,m.Sa)(a,0,e)));return a};
var jL=function(a){(0,m.Zl)(a,function(a,c){var d=(0,window.parseInt)((0,m.K)(a,"index"),10),e=(0,window.parseInt)((0,m.K)(c,"index"),10);return d-e});return a};var kL=function(a){var b=(0,m.w)("SHUFFLE_VALUE");if(!b){var c=0;(0,m.A)(a,function(a){(0,m.C)(a,HK)&&(c=(0,m.K)(a,"index"))});b=(c<<8)+Math.floor(256*Math.random());(0,m.Ya)("SHUFFLE_VALUE",b)}return b};
var mL=function(a,b){var c=null;(0,m.A)(a,function(a){(0,m.C)(a,HK)&&(c=a)});if(c){var d=(0,m.Cl)(c);d||(d=a[0]);var e=(0,m.Bl)(c);e||(e=a[a.length-1]);var f=EK,h=FK;f&&d&&(d={v:(0,m.K)(d,"video-id")},b?d.shuffle=b:-1!=f.href.indexOf("shuffle=")&&(d.shuffle=0),f.href=(0,m.fl)(f.href,d));h&&e&&(d={v:(0,m.K)(e,"video-id")},b?d.shuffle=b:-1!=h.href.indexOf("shuffle=")&&(d.shuffle=0),h.href=(0,m.fl)(h.href,d))}};
var cL=function(a,b,c,d){var e=(0,m.w)("EVENT_ID");e&&(e={ei:e},b&&(e.feature=b),c&&(e.ved=c),(b=(0,m.w)("SHUFFLE_VALUE"))&&(e.shuffle=b),KK||(e.autoplay_disabled=!0),d&&(e.playnext=(0,m.w)("LIST_AUTO_PLAY_VALUE"),e.autonav=1,d=uK(),0<d&&(e.lact=d)),(0,m.Cd)(a,e))};var hL=function(a){BK&&(0,m.kl)(BK,"autoplay-countdown",a)};
var YK=function(){var a=(0,m.I)("playlist-videos-list"),b=(0,m.I)(HK,a);if(b){var c=m.Qr.getInstance();if(a&&b){var d=(0,m.P)((0,m.V)(c,"scroll-unit"),a),b=(0,m.Na)(d,b);if(0<=b&&!(!a||(0,window.isNaN)(b)||0>b)&&(c=(0,m.P)((0,m.V)(c,"scroll-unit"),a),!(0>=c.length))){b>=c.length&&(b=c.length-1);var d=MI(c),e=a.offsetHeight,f=Math.max(Math.floor(a.scrollTop/d),0);b>f-1&&(d=Math.floor(e/d),e=c.length,b+d>e&&(b=e-d+1));0>b&&(b=0);b=c[b].offsetTop;a&&!(0,window.isNaN)(b)&&(0>b&&(b=0),a.scrollTop=b,(0,m.kl)(a,
"scroller-offset",b+""),m.Cr.g(a))}}}};
var oL=function(){if(!pL){var a=(0,m.q)("ytplayer.config");if(a&&(a=(0,m.td)(a),pL=(0,m.Tf)("player-api")||(0,m.Of)("player-api",a))){var b=pL;b.addEventListener("onReady",qL);b.addEventListener("onStateChange",rL);b.addEventListener("RATE_SENTIMENT",sL);b.addEventListener("SHARE_CLICKED",tL);b.addEventListener("SIZE_CLICKED",uL);b.addEventListener("onError",vL);b.addEventListener("onFullscreenChange",wL);b.addEventListener("onAdStart",xL);(0,m.EH)(pL,a.args.has_mdx_screens,!0);yL();zL=(0,m.bb)(yL,
1E3);a=pL.getAdState&&pL.getAdState();if(1==a||0==a)AL=!0;BL.push((0,m.z)("navigate",CL));BL.push((0,m.z)("player-shortcut-rewind",DL));BL.push((0,m.z)("player-shortcut-fast-forward",EL));BL.push((0,m.z)("player-shortcut-play-pause",FL));BL.push((0,m.z)("watch-list-change",GL));BL.push((0,m.z)("player-ad-start",HL));(0,m.MH)(pL);IL.push((0,m.z)("sentiment-like",(0,m.t)(m.Nn,"like")),(0,m.z)("sentiment-dislike",(0,m.t)(m.Nn,"dislike")),(0,m.z)("sentiment-indifferent",(0,m.t)(m.Nn,"indifferent")));
(0,m.JL)(NJ)}}};
var KL=function(){(0,m.cb)(zL);(0,m.Tk)(window,"beforeunload",LL);(0,m.nb)(IL);IL=[];(0,m.LH)();(0,m.WH)();if(pL){var a=pL;a.removeEventListener("onReady",qL);a.removeEventListener("onStateChange",rL);a.removeEventListener("RATE_SENTIMENT",sL);a.removeEventListener("SHARE_CLICKED",tL);a.removeEventListener("SIZE_CLICKED",uL);a.removeEventListener("onError",vL);a.removeEventListener("onFullscreenChange",wL);a.removeEventListener("onAdStart",xL)}pL=null;ML=AL=!1;NL="";OL={};(0,m.nb)(BL);BL.length=0;
for(a=PL.length;a--;)(0,m.y)(PL[a])};var GL=function(){var a=pL;a&&a.isReady()&&a.updatePlaylist()};var HL=function(){AL=!0};var QL=function(a,b){var c=RL();if(c){var d=(0,m.zd)(c,"").split(","),d=(0,m.rb)(d,function(b){return 0!=b.indexOf(a)&&!!b.length});4<=d.length&&d.shift();d.push(a+":"+b);(0,m.xd)(c,d.join(","),1814400)}};var SL=function(a){var b=RL();if(b){var c=(0,m.zd)(b,"").split(","),c=(0,m.rb)(c,function(b){return 0!=b.indexOf(a)});0==c.length?(0,m.il)(b):(0,m.xd)(b,c.join(","),1814400)}};
var TL=function(a){var b=(0,m.KG)();if(b){a&&(0,m.Ya)("RESUME_COOKIE_NAME",a);a=(0,m.w)("VIDEO_ID");var c=b.getDuration(),b=Math.floor(b.getCurrentTime());0==c||120>=b||b+120>=c?SL(a):QL(a,Math.floor(b))}};var LL=function(){var a=pL;a&&a.sendAbandonmentPing&&a.sendAbandonmentPing();if(RL()&&(TL(),(0,m.w)("IS_RESUMABLE_PLAYBACK"))){var b=pL;if(b){var a=(0,m.w)("VIDEO_ID"),c=b.getDuration(),b=Math.floor(b.getCurrentTime());0==c||20>=b||(0,m.pc)("/save_resume_204?"+(0,m.nc)({v:a,t:b.toString()}))}}};
var qL=function(a){UL(a);(0,m.L)(window,"beforeunload",LL);VL(a.getPlayerState());var b=(0,m.w)("RELATED_PLAYER_ARGS");b&&a&&a.updateVideoData&&a.updateVideoData(b)};var rL=function(a){1==a&&UL(pL);VL(a);(0,m.B)("player-state-change",a)};var UL=function(a){(0,m.B)("player-quality-data-update",a.getAvailableQualityLevels())};var vL=function(a){(0,m.B)("player-error",a)};
var wL=function(a){if(!a.fullscreen){var b=(0,m.w)("VIDEO_ID"),c=b==a.videoId;b&&!c&&(a=(0,m.fl)(window.location.href,{v:a.videoId,list:a.listId}),(0,m.Gd)(a))}};var uL=function(a){var b=(0,m.HC)();b&&b.getLoungeToken()||((0,m.w)("STAGE_MODE_AS_DEFAULT")?(0,m.xd)("wide_stage",a?"1":"0"):(0,m.xd)("wide",a?"1":"0"));(0,m.B)("player-resize",a)};var sL=function(a){(0,m.ka)(a)&&(a={videoId:(0,m.w)("VIDEO_ID"),sentiment:a});(0,m.B)("player-sentiment",a.videoId,a.sentiment)};var tL=function(){(0,m.B)("player-share")};
var xL=function(a){(0,m.B)("player-ad-start",a)};var WL=function(a){function b(){a.apply(this,arguments);c&&(0,m.nb)(c);d&&(0,m.nb)(d);(0,m.y)(void 0)}var c,d;(c=XL(b))&&(d=(0,m.JL)(b))};var XL=function(a){var b=null;AL?a():(b=(0,m.z)("player-ad-start",a),BL.push(b));return b};m.JL=function(a){var b=null;ML?a():(b=(0,m.z)("player-playback-start",a),BL.push(b));return b};m.YL=function(){var a=pL;a&&a.pauseVideo()};var FL=function(){var a=pL;a&&(2==a.getPlayerState()?a.playVideo():a.pauseVideo())};
var EL=function(){var a=pL;if(a){var b=a.getCurrentTime();a.seekTo(b+10)}};var DL=function(){var a=pL;if(a){var b=a.getCurrentTime();a.seekTo(b-10)}};var ZL=function(a,b){var c=pL;if(c){var d=null!=b?b:!0;c.seekTo(a,!0);d&&window.scroll(0,0);2==c.getPlayerState()&&c.playVideo()}};
var yL=function(){if(pL&&pL.isReady()){var a=window.location.hash;if(a!=NL){NL=a;a=(0,m.oj)(a);if("t"in a&&a.t!=OL.t){var b=a.t,c=0;-1!=b.indexOf("h")&&(b=b.split("h"),c=3600*b[0],b=b[1]);-1!=b.indexOf("m")&&(b=b.split("m"),c=60*b[0]+c,b=b[1]);-1!=b.indexOf("s")?(b=b.split("s"),c=1*b[0]+c):c=1*b+c;ZL(c,!1)}OL=a}}};var CL=function(){(0,m.cb)(zL)};var VL=function(a){ML||1!=a&&2!=a&&0!=a||(ML=!0,(0,m.B)("player-playback-start"))};var RL=function(){return(0,m.w)("RESUME_COOKIE_NAME")};
var $L=function(a,b,c){this.b=a;this.j=b;this.B=this.N=this.ha=this.S=this.ea=this.O=this.da=this.la=this.V=this.A=this.F=this.D=this.g=this.k=this.J=this.C=null;this.N=(0,m.U)("/playlist_ajax",{W:{action_get_addto_panel:1,video_id:this.j},onSuccess:function(a,b){aM(this,b.html);c()},context:this})};
var aM=function(a,b){a.b.innerHTML=b;a.J=(0,m.I)("sort-playlists",a.b);a.k=(0,m.I)("playlist-items",a.b);a.g=(0,m.I)("added-to-message",a.b);a.D=(0,m.I)("messages-area",a.b);a.F=(0,m.I)("create-playlist",a.b);a.F&&(a.A=(0,m.I)("new-playlist-title",a.b),a.V=(0,m.I)("create-new-playlist",a.b));a.la=(0,m.L)(a.J,"change",(0,m.s)(a.En,a));a.da=(0,m.L)(a.F,"submit",(0,m.s)(a.In,a));a.O=(0,m.R)(a.b,"click",(0,m.s)(a.Gn,a),"playlist-item");a.ea=(0,m.R)(a.b,"click",(0,m.s)(a.Hn,a),"save-note");a.S=(0,m.R)(a.b,
"click",(0,m.s)(a.Fn,a),"cancel-note");a.ha=(0,m.L)(a.A,"keyup",(0,m.s)(a.Jn,a));bM(a,a.J.value);(0,m.dq)()};var cM=function(a){(0,m.M)(a.la);(0,m.M)(a.da);(0,m.M)(a.O);(0,m.M)(a.ea);(0,m.M)(a.S);(0,m.M)(a.ha)};var bM=function(a,b){var c={updated:(0,m.t)(a.Zk,"time-updated-index"),created:(0,m.t)(a.Zk,"time-created"),privacy:a.zs,"a-z":a.$k,"z-a":a.As}[b];if(c){var d=(0,m.Ra)((0,m.P)("playlist-item",a.k));dM(a,d.sort((0,m.s)(c,a)))}};
var dM=function(a,b){var c=window.document.createDocumentFragment();(0,m.A)(b,function(a){c.appendChild(a)});(0,m.Tb)(a.k);(0,m.si)(a.k,c)};var eM=function(a){return"true"==((0,m.K)(a,"is-private")||"").toLowerCase()?0:"true"==((0,m.K)(a,"is-unlisted")||"").toLowerCase()?1:2};
var fM=function(a,b){(0,m.D)(b,"loading");(0,m.S)(a.g);a.B=(0,m.Qm)(b,{context:a,onSuccess:function(a,d){(0,m.F)(b,"loading");d.html?(cM(this),aM(this,d.html),d.show_feed_privacy_dialog&&(0,m.B)("SHOW-FEED-PRIVACY-ADD-TO-PLAYLIST-DIALOG",d.video_id,d.playlist_id)):d.errors&&this.Ac(d.errors[0],!0)}})};var gM=function(a,b){var c=(0,m.I)("playlist-video-count",a);c.innerHTML=(0,window.parseInt)(c.innerHTML,10)+b};
var hM=function(a,b){(0,m.D)(b,"loading");(0,m.Qm)(b,{P:{session_token:(0,m.T)(),set_video_id:a.C},context:a,onSuccess:function(){iM(this);(0,m.F)(b,"loading")},onError:function(a,d){(0,m.F)(b,"loading");this.Ac(d.errors[0],!0)}})};var iM=function(a){var b=(0,m.I)("selected",a.b);b&&((0,m.F)(b,"selected"),a.C=null)};var jM=function(){QI(function(){kM()})};var kM=function(){lM.GOOGLE_JSAPI=!0;(0,m.A)(mM.GOOGLE_JSAPI,function(a){a.call()});delete mM.GOOGLE_JSAPI};
var nM=function(a){this.k=a;this.j=[];this.D=this.zg=!1;this.B=this.b=this.A=this.g=null;var b=(0,m.s)(this.F,this),c=(0,m.w)("HL_LOCALE")||"en";if(a=oM.GOOGLE_JSAPI)lM.GOOGLE_JSAPI?b.call():(mM.GOOGLE_JSAPI||(mM.GOOGLE_JSAPI=[]),mM.GOOGLE_JSAPI.push(b),pM.GOOGLE_JSAPI||(jM(),b={callback:"yt.net.apiloader.onApiLoaded_GOOGLE_JSAPI"},c&&(b.language=c),a=(0,m.oc)(a,b),c=window.document.createElement("script"),c.src=a,window.document.body.appendChild(c),pM.GOOGLE_JSAPI=!0))};
var qM=function(a,b){var c=(0,m.H)("stats-optout-form");c&&((0,m.S)("stats-optout-success"),(0,m.S)("stats-optout-error"),a.B=(0,m.Qm)(c,{format:"XML",W:{opt_out:b},onSuccess:function(){this.zg=b;(0,m.N)("stats-optout-success")},onError:function(){(0,m.H)("stats-opt-out-chbox").checked=!this.zg;(0,m.N)("stats-optout-error")}}))};var rM=function(a,b){var c=(0,m.K)(a,b);if(c){var d=(0,m.O)(a,"watch-actions-stats-rats"),e=(0,m.K)(d,"current-"+b);e!=c&&((0,m.Jl)(d,e,c),(0,m.kl)(d,"current-"+b,c))}};
var sM=function(a,b,c){a=(0,m.I)("watch-actions-stats-rats",a.k);if(!a)return null;b=(0,m.K)(a,"current-"+b);return c&&b&&0==b.lastIndexOf(c,0)?b.substr(c.length):b};var tM=function(a){if(a.g&&a.D&&a.A){var b=sM(a,"metric-css","stats-metric-"),c=sM(a,"mode-css","stats-mode-");b&&c&&(a.b||(a.b=new window.google.visualization.LineChart(a.A)),uM(a,a.b,a.A,a.g.day||{},b in a.g?a.g[b][c]||{}:{}))}};
var uM=function(a,b,c,d,e){var f=new window.google.visualization.DataTable;f.addColumn("date","Date");f.addColumn("number","value");"cmp_data"in e?(f.addColumn("number","cmp_data"),d=fJ(d.data||[],e.data||[],e.cmp_data||[])):d=fJ(d.data||[],e.data||[]);(0,m.A)(d,function(a){a[0]=vM(a[0]);f.addRow(a)});e=e.opt||{};"hAxis"in e&&"viewWindow"in e.hAxis&&(d=e.hAxis.viewWindow,"min"in d&&!(d.min instanceof Date)&&(d.min=vM(d.min)),"max"in d&&!(d.max instanceof Date)&&(d.max=vM(d.max)));d=(0,m.Al)(c);(0,m.Ub)(c);
c.style.left="-5000px";(0,m.si)(a.k,c);try{b.draw(f,e)}catch(h){throw h;}finally{c.style.left="",(0,m.Ub)(c),d&&(0,m.si)(d,c)}};var vM=function(a){return new Date(a+6E4*(new Date(a)).getTimezoneOffset())};
var wM=function(a,b){this.C=a;this.J=b;this.j=(0,m.H)("watch-like-dislike-buttons");this.g="action-panel-details";var c=(0,m.K)(this.j,"vote-state"),c=(0,window.parseInt)(c,10);(0,window.isNaN)(c)&&(c=2);(0,m.jl)(this.j,"vote-state");this.k=c;this.b=[];this.La=[];this.xg=this.B=this.A=null;this.D=this.mi=0;this.F=!1;this.La.push((0,m.z)("player-share",this.ri,this));this.La.push((0,m.z)("player-state-change",this.an,this));this.La.push((0,m.z)("player-sentiment",this.Ym,this));this.La.push((0,m.z)("livestreaming-likes-updated",
this.$m,this));this.b.push((0,m.R)(this.C,"click",(0,m.s)(this.qi,this),"action-panel-trigger"));(0,m.C)(window.document.body,"watch8")&&(c=(0,m.H)("action-panel-overflow-menu"))&&this.b.push((0,m.R)(c,"click",(0,m.s)(this.qi,this),"action-panel-trigger"));(0,m.w)("LOGGED_IN")&&(c=(0,m.H)("watch-dislike"),this.b.push((0,m.L)((0,m.H)("watch-like"),"click",(0,m.s)(this.Xm,this))),this.b.push((0,m.L)(c,"click",(0,m.s)(this.Wm,this))));this.La.push((0,m.z)("watch-video-liked",(0,m.s)(this.Zm,this)));
xM(this,this.g);c=(0,m.oj)(window.location.hash).action;"share"==c?this.ri():"flag"==c?yM(this,"action-panel-report"):"stats"==c&&yM(this,"action-panel-stats");(0,m.w)("RECIPROCAL_CIRCLE_ADD_PROMO")&&zM(this)};var AM=function(a){switch(a){case "action-panel-share":(0,m.Kn)("share")}};var BM=function(){var a=(0,m.I)("yt-uix-button-toggled",(0,m.H)("action-panel-share")),b;iL()&&a?b=(0,m.K)(a,"video-id"):b=(0,m.w)("VIDEO_ID");return b};
var CM=function(){var a=null;if(iL()){var b=(0,m.H)("share-with-playlist");if(!b||b&&b.checked)a=(a=GK)?(0,m.K)(a,"full-list-id"):""}return a};
var DM=function(a,b,c){var d=0==a.k;EM(!1);bJ(b,c,{Er:(0,m.w)("PLAYBACK_ID"),zk:(0,m.w)("STATION_ID"),onSuccess:(0,m.s)(function(a,f){var h;t:switch(c){case 1:h="sentiment-dislike";break t;case 0:h="sentiment-like";break t;default:h="sentiment-indifferent"}(0,m.B)(h,b);0==c?((0,m.B)("watch-video-liked"),(0,m.Sl)(this.j,"disliked","liked")):1==c?((0,m.B)("watch-video-disliked"),(0,m.Sl)(this.j,"liked","disliked")):(0,m.Vl)(this.j,["liked","disliked"]);h=(0,m.H)("watch-like");var k;if(k=0==c?(0,m.K)(h,
"unlike-tooltip"):(0,m.K)(h,"like-tooltip"))(0,m.jl)(h,"tooltip-text"),h.title=k;this.k=c;0==c?((0,m.B)("yt-uix-videolike-liked"),"True"==f.show_feed_privacy_dialog&&(0,m.B)("SHOW-FEED-PRIVACY-LIKE-DIALOG",b)):d&&(0,m.B)("yt-uix-videolike-unliked")},a),onError:(0,m.s)(function(){FM(this,"action-panel-error")},a),aa:(0,m.s)(function(){EM(!0)},a)})};var EM=function(a){var b=(0,m.H)("watch-like-dislike-buttons");(0,m.x)(function(){(0,m.al)(b,a)},0)};var GM=function(a,b){yM(a,"action-panel-share",b)};
var yM=function(a,b,c){var d=(0,m.H)("watch7-secondary-actions");PI(m.$n.getInstance(),d);var d=(0,m.H)(b),e=HM(a,d);d&&e&&((0,m.D)(e,"yt-uix-button-toggled"),xM(a,b,c))};var IM=function(a){return(0,m.w)("LOGGED_IN")?(0,m.w)("YPC_CAN_RATE_VIDEO")?!0:(FM(a,"action-panel-rental-required"),!1):(FM(a,"action-panel-login"),!1)};
var xM=function(a,b,c){if("action-panel-none"!=b){var d=(0,m.H)(b);if(d){var e=!!(0,m.K)(d,"auth-required"),d=!!(0,m.K)(d,"panel-loaded");if(e&&!(0,m.w)("LOGGED_IN"))FM(a,"action-panel-login");else if(d)FM(a,b);else switch(b){case "action-panel-details":JM(a);break;case "action-panel-share":KM(a,c);break;case "action-panel-addto":b=(0,m.H)("action-panel-addto");c=new $L(b,(0,m.w)("VIDEO_ID"),m.ea);(0,m.Ua)(a,c);(0,m.kl)(b,"panel-loaded","true");FM(a,"action-panel-addto");break;case "action-panel-transcript":LM(a);
break;case "action-panel-add-transcript":b=(0,m.H)("action-panel-add-transcript");(0,m.N)((0,m.H)("watch-actions-add-transcript"));(0,m.kl)(b,"panel-loaded","true");FM(a,"action-panel-add-transcript");break;case "action-panel-stats":MM(a);break;case "action-panel-report":NM(a)}}}};
var JM=function(a){var b=(0,m.H)("action-panel-details"),c=(0,m.H)("watch-description");a.b.push((0,m.Vk)((0,m.H)("watch-description-content"),"click",function(){(0,m.F)(c,"yt-uix-expander-collapsed")}));(0,m.kl)(b,"panel-loaded","true");FM(a,"action-panel-details")};
var KM=function(a,b){var c=BM(),d=CM(),e=(0,m.H)("action-panel-share"),f=new m.xH((0,m.H)("watch-actions-share-panel"),c,d,function(){(0,m.S)("watch-actions-share-loading")},!0,null,b,!1,(0,m.w)("SHARE_REFERER"),(0,m.w)("SHARE_CAPTION"),null,null,null,null,(0,m.w)("PLAYLIST_INDEX"));(0,m.Ua)(a,f);(0,m.cb)(a.D);var h=(0,m.bb)(function(){var a=(0,m.KG)(),b=(0,m.cj)(e);if(a&&b){var a=a.getCurrentTime(),b=Math.floor(a/3600),c=Math.floor(a%3600%60),a=(0<b?b+":":"")+(0,m.em)(Math.floor(a%3600/60),0<b?2:
1)+":"+(0,m.em)(c,2);f.Fe(a)}else(0,m.cb)(h)},1E3);a.D=h;(0,m.kl)(e,"panel-loaded","true");FM(a,"action-panel-share")};var MM=function(a){var b=(0,m.H)("action-panel-stats");if(b){var c=new nM(b);(0,m.Ua)(a,c);a.B=XI((0,m.s)(function(a,e,f){f?(b.innerHTML=a,c.load(e)):FM(this,"action-panel-error")},a));(0,m.kl)(b,"panel-loaded","true");FM(a,"action-panel-stats")}};
var NM=function(a){var b,c=!1,d=!1,e=(0,m.H)("action-panel-report"),f=(0,m.s)(function(){FM(this,"action-panel-error")},a);(0,m.Ve)((0,m.w)("REPORTVIDEO_CSS"));(0,m.jd)((0,m.w)("REPORTVIDEO_JS"),(0,m.s)(function(){this.ca()||(c=!0,d&&c&&OM(e,b))},a));a.A=YI((0,m.s)(function(a,k){k?(d=!0,b=a,d&&c&&OM(e,b)):f()},a));(0,m.kl)(e,"panel-loaded","true");FM(a,"action-panel-report")};var OM=function(a,b){a.innerHTML=b;(0,m.q)("yt.www.report.reportvideo.init")(!0)};
var LM=function(a){var b=(0,m.H)("action-panel-transcript");(0,m.q)("yt.www.watch.transcript.open")(function(){(0,m.S)("watch-actions-transcript-loading");(0,m.N)((0,m.H)("watch-actions-transcript"))});(0,m.kl)(b,"panel-loaded","true");FM(a,"action-panel-transcript")};
var FM=function(a,b){var c=PM[b],d=(0,m.H)(b),e,f,h=(0,m.C)(window.document.body,"watch8");"action-panel-details"==a.g&&h?(e=c,f=d,a.g=b):(e=PM[a.g],f=(0,m.H)(a.g));var k=a.J;h&&"action-panel-details"!=b&&(0,m.N)(k);if(c==e)(0,m.F)(k,"action-panel-transition"),(0,m.Vl)(f,["action-panel-center","action-panel-left","action-panel-right"]),(0,m.N)(f);else if(a.g=b,h)(0,m.S)(f),(0,m.N)(d);else{(0,m.N)(f);k.style.height=k.clientHeight+"px";(0,m.D)(k,"action-panel-transition");if(c>e)var n="action-panel-right",
u="action-panel-left";else n="action-panel-left",u="action-panel-right";(0,m.D)(f,"action-panel-center");(0,m.D)(d,n);(0,m.N)(d);(0,m.x)(function(){(0,m.F)(f,"action-panel-center");(0,m.D)(f,u);(0,m.F)(d,n);(0,m.D)(d,"action-panel-center");this.mi=(0,m.x)(function(){(0,m.S)(f);(0,m.F)(f,u);(0,m.F)(d,"action-panel-center");(0,m.F)(k,"action-panel-transition");k.style.height=""},(0,m.JG)(d))},0)}};
var HM=function(a,b){var c=(0,m.P)("action-panel-trigger",a.C);return(0,m.Ka)(c,function(a){a=(0,m.K)(a,"trigger-for");return b.id==a})};
var zM=function(a){var b=(0,m.I)("yt-uix-clickcard-target",(0,m.H)("watch7-user-header")),c=(0,m.I)("rcap-dismiss-button",window.document);(0,m.Wt)("plus:follow",(0,m.Xt)(function(){var a=(0,m.I)("add-to-circle"),b=(0,m.q)("gapi.follow.render");b&&a&&(b(a,{href:(0,m.K)(a,"gplus-profile-url"),height:24,source:"youtube:topfans-follow-back"}),a.style.zIndex=2147483647)}));a.b.push((0,m.L)(c,"click",function(){this.xg=(0,m.U)("/engagement_wizard_ajax",{method:"POST",W:{action_dismiss_reciprocal_circle_add_promo:"1"},
P:{session_token:(0,m.T)(),video_id:(0,m.w)("VIDEO_ID")}})}));m.Do.getInstance().show(b)};var QM=function(){this.b=[];this.g=0;this.k=window.document.title;this.j=!0;(0,m.KG)()&&this.Zi(1);this.b.push((0,m.z)("page-resize",this.qo,this));this.b.push((0,m.z)("player-state-change",this.Zi,this));this.b.push((0,m.z)("player-resize",this.to,this));this.b.push((0,m.z)("player-quality-data-update",this.ro,this));this.le()};var RM=function(a){1==a&&(0,m.BD)()};
var SM=function(){if(TM=(0,m.H)("watch7-preview"))(0,m.ZC)(),UM.push((0,m.R)(TM,"click",VM,"watch-queue-preview-playlist-checkbox")),UM.push((0,m.R)(TM,"click",WM,"preview-play-now-button")),UM.push((0,m.R)(TM,"click",XM,"preview-play-all-now-button")),UM.push((0,m.R)(TM,"click",YM,"preview-addto-queue-button")),UM.push((0,m.R)(TM,"click",ZM,"preview-addto-queue-button-success")),UM.push((0,m.R)(TM,"click",YM,"preview-addto-queue-button-error")),UM.push((0,m.R)(TM,"click",$M,"overflow-menu-choice")),
aN.push((0,m.z)("watch-queue-show",function(){bN()?cN():dN()})),aN.push((0,m.z)("watch-queue-hide",dN)),aN.push((0,m.z)("watch-queue-update",eN)),bN()&&cN()};var cN=function(){if(!(0,m.cj)(TM)){var a=(0,m.w)("VIDEO_ID"),b=(0,m.w)("LIST_ID");(0,m.mk)(TM)?(fN(),eN(),(0,m.N)(TM)):(a={action_get_watch_queue_preview:1,v:a},b&&(a.list=b),(0,m.U)("/watch_queue_ajax",{method:"GET",W:a,onSuccess:gN}))}};var dN=function(){(0,m.S)(TM)};var hN=function(){return(0,m.C)(TM,"preview-playlist-mode")};
var eN=function(){if((0,m.mk)(TM)&&!hN()){var a=xK(),a=(0,m.Ma)(a,(0,m.w)("VIDEO_ID"));(0,m.De)(iN,a);(0,m.De)(jN,!a);(0,m.S)(kN)}};var VM=function(a){(0,m.sb)(TM,"preview-playlist-mode",a.currentTarget.checked)};var WM=function(){(0,m.B)("watch-queue-addto-video-play-now",(0,m.w)("VIDEO_ID"))};var XM=function(){(0,m.B)("watch-queue-addto-playlist-play-now",(0,m.w)("LIST_ID"),(0,m.w)("VIDEO_ID"))};
var YM=function(){var a=(0,m.w)("VIDEO_ID"),b=(0,m.w)("LIST_ID");hN()?(0,m.iD)(b,function(){(0,m.N)(iN);(0,m.S)(jN);(0,m.S)(kN);(0,m.B)("watch-queue-addto-playlist-added")},function(){(0,m.N)(kN);(0,m.S)(iN);(0,m.S)(jN)}):(0,m.eD)(a,function(){(0,m.N)(iN);(0,m.S)(jN);(0,m.S)(kN);(0,m.B)("watch-queue-addto-video-added")},function(){(0,m.N)(kN);(0,m.S)(iN);(0,m.S)(jN)})};
var ZM=function(){var a=(0,m.w)("VIDEO_ID");hN()?(0,m.jD)(function(){(0,m.N)(jN);(0,m.S)(iN);(0,m.S)(kN);(0,m.B)("watch-queue-addto-playlist-removed")},function(){(0,m.N)(kN);(0,m.S)(iN);(0,m.S)(jN)}):(0,m.hD)(a,function(){(0,m.N)(jN);(0,m.S)(iN);(0,m.S)(kN);(0,m.B)("watch-queue-addto-video-removed")},function(){(0,m.N)(kN);(0,m.S)(iN);(0,m.S)(jN)})};var $M=function(a){var b=(0,m.K)(a.currentTarget,"action");lN[b](a.currentTarget)};
var fN=function(){var a=(0,m.MC)();if(a){var b=(0,m.I)("video-receiver",TM);b&&(0,m.zl)(b,a.name)}};var gN=function(a,b){if(TM&&!(0,m.mk)(TM)&&a.responseText&&b.html){var c=(0,m.xj)(b.html);TM.innerHTML="";TM.appendChild(c);fN();jN=(0,m.I)("preview-addto-queue-button",TM);iN=(0,m.I)("preview-addto-queue-button-success",TM);kN=(0,m.I)("preview-addto-queue-button-error",TM);bN()?(fN(),eN(),(0,m.N)(TM)):dN()}};var bN=function(){var a=(0,m.mk)((0,m.H)("watch-queue-mole"))?0:1;return vK()&&wK()&&0==a};
var mN=function(a,b){var c=(0,m.oc)("/related_ajax",{continuation:a,action_more_related_videos:1});window.spf.load(c,{onSuccess:b})};var nN=function(a){var b=(0,m.I)("related-video",a),b={video_id:(0,m.K)(b,"video-id"),action_dismiss_video_recommendation:1},b=(0,m.oc)("/related_ajax",b);window.spf.load(b,{method:"POST",onSuccess:function(){(0,m.S)(a)}})};var oN=function(a){a.stopPropagation();a=a.currentTarget;var b=(0,m.O)(a,"video-list-item");if(b)switch((0,m.K)(a,"action")){case "hide":nN(b)}};
var pN=function(a){var b=a.currentTarget.href,c=(0,m.KG)();if(c){var d=(0,m.gl)(b).v;if((0,m.w)("VIDEO_ID")==d){c=Math.floor(c.getCurrentTime());a=a.currentTarget;var c={t:c},d=b.split("#",2),b=d[0],d=1<d.length?"#"+d[1]:"",e=(0,m.oj)(d),f;for(f in c)e[f]=c[f];(0,m.pk)(e)||(d=(0,m.Rj)("#",e));a.href=b+d}}};var qN=function(a){(0,m.li)(a.target,"BUTTON")||a.currentTarget.click()};var rN=function(a){sN.guide=(0,m.x)(function(){(0,m.I)("guide-module-loading")&&((0,m.M)(tN.ov),uN(a,"time",!1))},3E3)};
var vN=function(a){var b=["related"];"playback"==a&&(WL((0,m.t)(uN,b,"play")),a=(0,m.w)("RELATED_DELAY_MAX",void 0)||1E4);(0,m.ka)(a)&&(sN.related=(0,m.x)(function(){uN(b,"time")},a))};
var wN=function(a){var b=(0,m.H)((0,m.w)("IS_ACTIVE_LIVE_VIDEO")&&!(0,m.w)("IS_DISTILLER")?"watch7-sidebar-discussion":"watch-discussion");if((0,m.lk)(b)){(0,m.D)(b,"scrolldetect");(0,m.kl)(b,"scrolldetect-callback","comments-delay-load");var c=(0,m.w)("WATCH_COMMENTS_LOAD_DELAY_PLAYBACK")?(0,m.J)()+1E4:(0,m.J)()+1E3;(0,m.rq)({"comments-delay-load":function(){(0,m.w)("WATCH_COMMENTS_LOAD_DELAY_PLAYBACK")&&WL((0,m.t)(uN,a,"play"));var b=c-(0,m.J)();sN.comments=(0,m.x)((0,m.t)(uN,a,0<b?"time":"scroll"),
b)}})}};
var uN=function(a,b,c){var d=(0,m.w)("VIDEO_ID");d||(0,m.Oa)(a,"comments");(0,m.Ma)(a,"comments")&&(0,m.BG)()&&(0,m.Oa)(a,"comments");if((0,m.w)("RELATED_DELAY_REVEAL")&&(0,m.Ma)(a,"related")){(0,m.Oa)(a,"related");var e=(0,m.H)("watch-reveal-related"),f=(0,m.H)("watch-related");e&&(e=e.innerHTML,e=e.replace(/^\s*(\x3c!--\s*)?/,""),e=e.replace(/(\s*--\x3e)?\s*$/,""),e=(0,m.xj)(e),f.appendChild(e));xN()}a&&a.length&&(f=(0,m.gl)(window.location.href),f.v=d,f.tr=b,(0,m.Ma)(a,"comments")&&(0,m.w)("IS_DISTILLER")&&(f.distiller=
"1"),(0,m.jv)(a,c,f,(0,m.t)(yN,a)))};
var yN=function(a){if((0,m.Ma)(a,"comments")){if((0,m.BG)())zN=!0;else{var b=(0,m.H)("comments-view");AN=new bK((0,m.H)("watch-discussion"));BN.push((0,m.R)(b,"click",gK,"comment-action"));if(b=(0,m.H)("comments-textarea"))b.disabled=!1,b.id="";(0,m.w)("COMMENT_OPEN_REPLY_BOX")&&(b=(0,m.P)("comment",(0,m.H)("linked-comments-header")),mK(b[b.length-1]));(0,m.Oq)((0,m.H)("comments-view"))}(b=(0,m.w)("JS_COMMENTS_MODULES"))&&(0,m.md)(b)}(0,m.Ma)(a,"related")&&(xN(),a=(0,m.w)("RELATED_PLAYER_ARGS"),b=
(0,m.KG)(),a&&b&&b.updateVideoData&&b.updateVideoData(a))};var xN=function(){AK();(0,m.Oq)((0,m.H)("watch-related"))};m.rH.prototype.Fe=(0,m.ci)(17,function(){if(this.Tl&&this.Ba){var a=(0,m.KG)(),b=Math.round(1E3*a.getCurrentTime()),b=[b,b+3E3],b=(0,m.sH)(this,b,!0);(0,m.vH)(this,b,1!=a.getPlayerState())}});m.xH.prototype.Fe=(0,m.ci)(16,function(a){!this.g||(0,m.ok)(this.g,"focused")||this.Da||(this.g.value=a,this.be(),(0,m.cj)(this.A)&&this.O&&this.O.Fe())});
var VI={html5_ajax:"html5_ajax_token",watch_actions_ajax:"watch_actions_ajax_token",addto_ajax:"addto_ajax_token",playlist_video_ajax:"playlist_video_ajax_token"},UI={html5_ajax:"action_get_html5_token",watch_actions_ajax:"action_get_watch_actions_token",addto_ajax:"action_get_wl_token",playlist_video_ajax:"action_get_html5_wl_token"},IL=[],CN,DN,iJ,kJ;m.g=gJ.prototype;m.g.Wc=!1;m.g.qe=!1;m.g.start=function(a){var b={start:0};b.end=a.scrollHeight-a.clientHeight;b.duration=b.end/3;b.ee="linear";this.g=new m.qw(a,b);this.Wc=!0;this.b.listen(a,"click",this.Vp);this.b.listen(a,"mouseover",this.Xp);this.b.listen(a,"mouseout",this.Up);this.b.listen(a,"scroll",this.Wp)};m.g.Wp=function(){this.qe||this.Wc||(this.g.pause(),this.qe=!0)};m.g.Vp=function(){this.g.pause();this.Wc=!1;this.qe=!0};m.g.Xp=function(){this.g.pause();this.Wc=!1};
m.g.Up=function(){this.Wc||this.qe||(this.g.play(),this.Wc=!0)};m.g.dispose=function(){this.b.removeAll();this.qe=this.Wc=!1;this.g=null;this.j=!0};m.g.ca=function(){return this.j};var GJ="",HJ="",JJ=!1,wJ=!1,yJ=null,lJ=null,KJ=0,pJ=null,qJ=null,rJ=null,xJ=!1;(0,m.l)("yt.www.watch.ads.setAdId",function(a){window.ad_debug=a},void 0);(0,m.l)("yt.www.watch.ads.setCompanion",zJ,void 0);(0,m.l)("yt.www.watch.ads.showForcedMpu",function(a){var b=AJ(a);a=CJ(a);zJ(b,a)},void 0);(0,m.l)("yt.www.watch.ads.setGutSlotSizes",function(a,b){if(pJ){var c=pJ.getSizes();(0,m.bm)(c);b&&c.push(qJ);a&&c.push(rJ)}},void 0);
(0,m.l)("yt.www.watch.ads.handleSetCompanion",function(a){a=a.replace(";dc_seed=",";kmyd=watch-channel-brand-div;dc_seed=");var b=AJ(a);a=CJ(a);zJ(b,a)},void 0);(0,m.l)("yt.www.watch.ads.handleSetCompanionForFreewheel",DJ,void 0);(0,m.l)("yt.www.watch.ads.handleSetAfvCompanionVars",EJ,void 0);(0,m.l)("yt.www.watch.ads.companionSetupComplete",FJ,void 0);(0,m.l)("yt.www.watch.ads.pauseVideo",IJ,void 0);(0,m.l)("yt.www.watch.ads.loadAfc",tJ,void 0);
(0,m.l)("yt.www.watch.ads.isAfcAdVisible",function(){var a=(0,m.H)("google_companion_ad_div");return a?(a=(0,m.mk)(a))&&"IFRAME"==a.tagName?(0,m.Ea)(a.src,"youtube.com/ad_frame"):!1:!1},void 0);(0,m.l)("yt.www.watch.ads.checkInit",uJ,void 0);(0,m.l)("yt.www.watch.ads.initVideoWallCompanionListeners",function(a,b){GJ=a;HJ=b;window.addEventListener("message",function(a){"companion-setup-complete"==a.data?FJ():"pause-video"==a.data&&IJ()},!1)},void 0);
(0,m.l)("yt.www.ads.pyv.pyvWatchAfcWithPpvCallback",function(a){aJ(a);0<a.length&&$I()},void 0);(0,m.l)("yt.www.ads.pyv.pyvWatchAfcCallback",aJ,void 0);(0,m.l)("yt.www.ads.pyv.pyvHomeAfcCallback",m.JE,void 0);(0,m.l)("yt.www.ads.pyv.showPpvOnWatch",RI,void 0);(0,m.l)("yt.www.ads.pyv.loadPyvIframe",ZI,void 0);(0,m.l)("yt.www.watch.ads.restrictioncookie.spr",function(a){(0,m.pc)(a+"mac_204?action_fcts=1");(0,m.xd)("CLAD","tlip="+(0,m.J)());return!0},void 0);(0,m.l)("setFreewheelCompanion",DJ,void 0);
(0,m.l)("setAfvCompanionVars",EJ,void 0);var MJ=null,OJ=!1;var fK,AN;m.g=SJ.prototype;m.g.destroy=function(){(0,m.M)(this.A);this.A=[];(0,m.A)(this.k,function(a){(0,m.cb)(a)});this.k=[];(0,m.jl)(this.na,"initialized")};m.g.focus=function(){this.gb.focus()};m.g.Di=function(){this.gb.readOnly||TJ(this)};m.g.rn=function(a){if(this.D)switch(a.keyCode){case 13:this.Ci(a);break;case 27:WJ(this)}};m.g.Ei=function(){(0,m.ok)(this.na,"has-focus")||(0,m.S)(this.Kc);(0,m.Aj)(this.na,"has-focus");(0,m.B)("comments-focus",this.na)};m.g.qn=function(){(0,m.B)("comments-blur",this.na)};
m.g.Ci=function(a){a.preventDefault();if(!this.kc.disabled){this.kc.disabled=!0;this.gb.readOnly=!0;a=(0,m.Qi)((0,m.Im)(this.na));a.screen=(0,m.nc)({h:window.screen.height,w:window.screen.width,d:window.screen.colorDepth});var b=a.comment,b={return_ajax:"true",len:b.length,wc:b.split(/\s+/).length};this.na.reply_parent_id.value&&(b.reply=1);this.j&&(b.tag=this.j);var c=(0,m.w)("PLAYBACK_ID");c&&(a.plid=c);(0,m.U)(this.na.action,{format:"XML",method:"POST",W:b,P:a,aa:function(a,b){var c=b.str_code;
switch(c){case "OK":c=window.document.createElement("ul");c.innerHTML=b.html_content;c=(0,m.mk)(c);if(this.na.reply_parent_id.value){var h=(0,m.li)(this.na,null,"comments-post-container"),k=(0,m.li)(h,null,"comment");(0,m.Ub)(h);(0,m.Jl)(k,"replying","has-child");(0,m.Aj)(c,"child");(0,m.nk)(c,"last",!(0,m.Cl)(k));(0,m.Fl)(c,k)}else this.nn?this.yi.appendChild(c):(0,m.El)(this.yi,c,0),WJ(this);(0,m.Wq)(c);(0,m.B)("comment-submit-success");"True"==b.show_feed_privacy_dialog&&(0,m.B)("SHOW-FEED-PRIVACY-COMMENT-DIALOG",
(0,m.w)("VIDEO_ID"),b.time_created);break;case "PENDING":XJ(this);this.xi.innerHTML=(0,m.hb)("COMMENT_PENDING");(0,m.Jl)(this.Kc,"yt-alert-error","yt-alert-info");(0,m.N)(this.Kc);break;default:aK(this,c,b)}this.gb.readOnly=!1},context:this})}};bK.prototype.destroy=function(){(0,m.M)(this.b);this.b=[]};bK.prototype.k=function(a){a.preventDefault();(0,m.ok)(a.currentTarget,"yt-uix-button-toggled")||((0,m.S)(this.Xi),(0,m.B)("comments-page-changing"),this.Le?this.g(2):cK(this,(0,m.s)(this.g,this,2)))};
bK.prototype.g=function(a){var b=(0,m.H)("comments-view");b.appendChild(this.Le);(0,m.Wq)(b);if(b=(0,m.H)("comments-textarea"))b.disabled=!1,b.id="";if(b=(0,m.I)("comment-list",this.$)){var c=(0,m.I)("live-comments-setting",this.$);(0,m.B)("comments-page-changed",b,c,a)}else(0,m.B)("comments-page-changed");cK(this)};var BN=[];var zN=!1;var qK=-2;var yK;var LK=[],RK=[],eL=0,IK=null,fL=!1,bL=!1,BK=null,OI=null,CK=null,DK=null,EK=null,FK=null,GK=null,HK="",gL=null,KK=!1;var pL,BL=[],AL=!1,ML=!1,NL="",OL={},zL=0,PL=[];(0,m.v)($L,m.Ta);m.g=$L.prototype;m.g.K=function(){this.N&&this.N.abort();this.B&&this.B.abort();cM(this);$L.H.K.call(this)};m.g.En=function(a){a=a.currentTarget.value;bM(this,a);(0,m.U)("/playlist_ajax?action_update_addto_sort_criteria=1",{W:{criteria:a}})};m.g.zs=function(a,b){var c=eM(a);return eM(b)-c};m.g.Zk=function(a,b,c){b=(0,window.parseInt)((0,m.K)(b,a),10)||window.Infinity;return((0,window.parseInt)((0,m.K)(c,a),10)||window.Infinity)-b};
m.g.$k=function(a,b){var c=(0,m.K)(a,"title")||"",d=(0,m.K)(b,"title")||"";return(0,m.Ej)(c,d)};m.g.As=function(a,b){return this.$k(b,a)};m.g.In=function(a){a.preventDefault();a=(0,m.I)("create-playlist",this.b);(0,m.Fj)(this.A.value)||fM(this,a)};
m.g.Gn=function(a){if(!(0,m.O)(a.target,"playlist-note-form"))if(a.stopPropagation(),iM(this),(0,m.S)(this.g),a=a.currentTarget,(0,m.C)(a,"contains-all-selected-videos")){var b=(0,m.K)(a,"full-list-id");(0,m.D)(a,"loading");(0,m.Gs)({ja:this.j,ed:b,onSuccess:(0,m.t)(this.Lq,a),onError:(0,m.t)(this.lk,a),context:this})}else b=(0,m.K)(a,"full-list-id"),(0,m.D)(a,"loading"),(0,m.Fs)({ja:this.j,ed:b,onSuccess:(0,m.t)(this.Kq,a),onError:(0,m.t)(this.lk,a),context:this})};
m.g.Lq=function(a,b,c){(0,m.Vl)(a,["loading","contains-all-selected-videos"]);gM(a,-1);c.html_content&&this.Ac(c.html_content,!1);(0,m.B)("PLAYLIST_UPDATED")};
m.g.Kq=function(a,b,c){b=c.result;this.C=b.set_video_ids[0];(0,m.Sl)(a,"loading","contains-all-selected-videos");gM(a,1);b.message&&this.Ac(b.message,!1);"True"==b.show_private_video_warning&&(c=(0,m.I)("private-video-warning",(0,m.I)("watch-playlist-drawer")))&&(0,m.N)(c);c=(0,m.K)(a,"list-type");var d="favorites"==c;d||"watch-later"==c||(0,m.D)(a,"selected");d?(a="playlist-favorite",c="SHOW-FEED-PRIVACY-FAVORITE-DIALOG"):(a="playlist-addto",c="SHOW-FEED-PRIVACY-ADD-TO-PLAYLIST-DIALOG");(0,m.B)(a,
this.j,b.full_list_id);"True"==b.show_feed_privacy_dialog&&(0,m.B)(c,this.j,b.full_list_id);(0,m.B)("PLAYLIST_UPDATED")};m.g.lk=function(a,b,c){(0,m.F)(a,"loading");this.Ac(c.errors[0],!0)};m.g.Hn=function(a){a.preventDefault();(0,m.S)(this.g);a=(0,m.O)(a.currentTarget,"playlist-note-form");hM(this,a)};m.g.Fn=function(){iM(this)};m.g.Ac=function(a,b){b?(0,m.uu)(a,this.g,this.D):(0,m.vu)("yt-alert-success",a,this.g,this.D)};m.g.Jn=function(){this.V.disabled=(0,m.Fj)(this.A.value)};var oM={GOOGLE_MAPS_API:"//maps.google.com/maps/api/js?sensor=false",GOOGLE_LANGUAGE_API_VIRTUAL_KEYBOARD:"//www.google.com/jsapi?key=youtube-internal-vk",GOOGLE_LANGUAGE_API_INPUT_TOOLS:"//www.google.com/jsapi?key=youtube-internal-it",GOOGLE_PLUS_ONE:"//apis.google.com/js/platform.js",GOOGLE_JSAPI:"//www.google.com/jsapi"},pM={},lM={},mM={};(0,m.v)(nM,m.Ta);nM.prototype.K=function(){(0,m.M)(this.j);this.j.length=0;this.B&&this.B.abort();this.b&&(this.b.clearChart(),this.b=null);nM.H.K.call(this)};
nM.prototype.load=function(a){var b=(0,m.H)("stats-opt-out-chbox");b&&(this.zg=!b.checked,this.j.push((0,m.L)(b,"change",(0,m.s)(function(){qM(this,!b.checked)},this))));this.j.push((0,m.R)(this.k,"click",(0,m.s)(function(a){rM(a.currentTarget,"mode-css");tM(this)},this),"stats-mode-button"));this.j.push((0,m.R)(this.k,"click",(0,m.s)(function(a){rM(a.currentTarget,"top-site-css");rM(a.currentTarget,"metric-css");tM(this)},this),"stats-bragbar"));(0,m.zs)(m.vs);a&&(this.g=(0,m.Bk)(a));this.A=(0,m.I)("stats-chart-gviz",
this.k);tM(this)};nM.prototype.F=function(){window.google.load("visualization","1.0",{packages:["corechart"],callback:(0,m.s)(this.C,this),language:(0,m.w)("HL_LOCALE")||"en"})};nM.prototype.C=function(){this.D=!0;tM(this)};(0,m.v)(wM,m.Ta);var PM={"action-panel-details":1,"action-panel-share":2,"action-panel-addto":3,"action-panel-transcript":4,"action-panel-stats":5,"action-panel-report":6,"action-panel-login":7,"action-panel-ratings-disabled":8,"action-panel-rental-required":9,"action-panel-error":10};m.g=wM.prototype;m.g.K=function(){(0,m.M)(this.b);this.b.length=0;(0,m.nb)(this.La);this.La.length=0;(0,m.y)(this.mi);(0,m.cb)(this.D);this.A&&this.A.abort();this.B&&this.B.abort();this.xg&&this.xg.abort();wM.H.K.call(this)};
m.g.Xm=function(){var a=0==this.k?2:0;IM(this)&&DM(this,(0,m.w)("VIDEO_ID"),a)};m.g.Wm=function(){var a=1==this.k?2:1;IM(this)&&DM(this,(0,m.w)("VIDEO_ID"),a)};m.g.Zm=function(){yM(this,"action-panel-share")};m.g.ri=function(){GM(this);AM("action-panel-share")};m.g.an=function(a){0==a?(0,m.w)("SHARE_ON_VIDEO_END")&&!this.F&&GM(this,!0):1==a&&(0,m.w)("SHARE_ON_VIDEO_START")&&GM(this,!0)};m.g.Ym=function(a,b){IM(this)&&DM(this,a,b)};
m.g.qi=function(a){a=(0,m.K)(a.currentTarget,"trigger-for");xM(this,a);this.F=!0;AM(a)};m.g.$m=function(a,b,c,d){var e=(0,m.H)("watch7-views-info"),f=(0,m.I)("likes-count",e);f&&(0,m.zl)(f,a);(a=(0,m.I)("dislikes-count",e))&&(0,m.zl)(a,b);if(b=(0,m.I)("video-extras-sparkbar-likes",e))b.style.width=c+"%";if(c=(0,m.I)("video-extras-sparkbar-dislikes",e))c.style.width=d+"%"};m.g=QM.prototype;m.g.dispose=function(){(0,m.y)(this.g);(0,m.nb)(this.b);this.b.length=0};m.g.qo=function(){this.le()};m.g.Zi=function(a){m.Eh||(window.document.title=1==a?"\u25b6 "+this.k:this.k)};
m.g.to=function(a){a=!!a;var b=(0,m.H)("watch7-container"),c=(0,m.H)("player"),d=(0,m.H)("watch7-sidebar"),e=(0,m.H)("page");if(b&&c&&d&&e)if(c=(0,m.JG)(d),a)(0,m.D)(b,"watch-wide"),(0,m.y)(this.g),this.g=(0,m.x)((0,m.s)(this.le,this),c);else if((0,m.F)(b,"watch-wide"),(0,m.D)(e,"watch-non-stage-mode"),(0,m.F)(e,"watch-stage-mode"),this.le(),(0,m.Wq)(d),a=(0,m.H)("watch7-playlist-tray-container"))a=(0,m.JG)(a),(0,m.x)(ZK,a)};
m.g.ro=function(a){(0,m.C)(window.document.body,"flexwatch-noupscale")&&(this.j=(0,m.Pg)(["large","hd720","hd1080"],function(b){return(0,m.Ma)(a,b)}),this.le())};
m.g.le=function(){(0,m.y)(this.g);var a=(0,m.H)("player"),b=(0,m.H)("watch7-container");if(b&&a){var c=(0,m.C)(b,"watch-wide"),b=(0,m.pp)();if(c){if(c=(0,m.H)("page"))(0,m.F)(c,"watch-non-stage-mode"),(0,m.D)(c,"watch-stage-mode");var c=!!(0,m.w)("ENABLE_AUTO_LARGE"),d=!1,e=!1;this.j&&(d=(0,m.C)(window.document.body,"appbar-flexwatch-mini"),e=(0,m.C)(window.document.body,"appbar-flexwatch-540")||(0,m.C)(window.document.body,"appbar-flexwatch-540-mini"));var f=1E3<=b.width&&b.height>=(d?690:740),b=
1320<=b.width&&b.height>=(d?870:920);c&&b?((0,m.Vl)(a,["watch-medium","watch-medium-540","watch-small"]),(0,m.D)(a,"watch-large")):e&&f?((0,m.Vl)(a,["watch-small","watch-medium","watch-large"]),(0,m.D)(a,"watch-medium-540")):((0,m.Vl)(a,["watch-small","watch-medium-540","watch-large"]),(0,m.D)(a,"watch-medium"))}else(0,m.Vl)(a,["watch-medium","watch-medium-540","watch-large"]),(0,m.D)(a,"watch-small"),this.j||(0,m.F)(window.document.body,"appbar-flexwatch")}};var EN=[];var TM,jN,iN,kN,lN={"play-next":function(){var a=(0,m.w)("VIDEO_ID"),b=(0,m.w)("LIST_ID");hN()?(0,m.B)("watch-queue-addto-playlist-play-next",b,a):(0,m.B)("watch-queue-addto-video-play-next",a)}},UM=[],aN=[];var FN=[];var GN=0,HN=[],IN=[];var tN={},sN={};(0,m.l)("yt.www.watch.player.init",oL,void 0);(0,m.l)("yt.www.watch.player.dispose",KL,void 0);(0,m.l)("yt.www.watch.player.seekTo",ZL,void 0);(0,m.l)("yt.www.watch.player.play",function(){var a=pL;a&&a.playVideo()},void 0);(0,m.l)("yt.www.watch.player.pause",m.YL,void 0);(0,m.l)("yt.www.watch.player.saveResumeOffset",TL,void 0);(0,m.l)("yt.www.watch.player.handleEndPreview",function(a){var b=pL;b&&b.stopVideo&&b.stopVideo();(b=(0,m.H)("watch-checkout-offers"))&&(0,m.Dw)(m.wI,new m.Kw(b,a))},void 0);
(0,m.l)("yt.tracking.social.onAdvertiserVideoView",m.In,void 0);(0,m.l)("yt.www.watch.related.loadMore",function(a){(0,m.S)("watch-more-related-button");(0,m.N)("watch-more-related");a=(0,m.K)(a,"continuation");mN(a,function(){var a=(0,m.H)("watch-more-related");(0,m.B)("yt-uix-load-more-success");(0,m.Wq)(a)})},void 0);(0,m.l)("yt.www.comments.initForm",function(a,b,c){eK(a,b,c)},void 0);(0,m.l)("yt.www.thumbnaildelayload.classifyAndLoadVisibleImages",m.Oq,void 0);
(0,m.l)("yt.www.watch.lists.loadThumbnails",ZK,void 0);
(0,m.l)("yt.www.watch.lists.getState",function(){var a=[],b={},c=-1,d=[],e=OI;if(!e)return null;(0,m.A)(e.getElementsByTagName("li"),function(e,h){(0,m.C)(e,HK)&&(c=h);var k=(0,m.K)(e,"video-id"),n=(0,m.K)(e,"video-username"),u=(0,m.K)(e,"video-title"),n={id:k,username:n,title:u},u=(0,m.K)(e,"video-clip-start"),E=(0,m.K)(e,"video-clip-end");a[h]=k;b[k]=n;d[h]={start:u,end:E}});e=GK;return{author:(0,m.K)(e,"list-author"),autoPlay:KK,clipRanges:d,index:c,list:(0,m.K)(e,"full-list-id"),listTitle:(0,m.K)(e,
"list-title"),listDescription:(0,m.K)(e,"list-description"),videoData:b,videoIds:a}},void 0);(0,m.l)("yt.www.watch.activity.getTimeSinceActive",uK,void 0);(0,m.l)("yt.www.watch.activity.setTimestamp",tK,void 0);(0,m.l)("yt.sharing.facebooktokenrefresh.finish",function(a){var b={session_token:(0,m.T)(),service:"facebook"},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);(0,m.U)("/social_connector_ajax",{method:"POST",format:"JSON",W:{action_connect_service:1},P:b})},void 0);
(0,m.l)("yt.abuse.invokeBotguard",function(){return MJ?MJ.invoke():null},void 0);(0,m.l)("yt.abuse.botguardInitialized",function(){return null!=MJ},void 0);
(0,m.Oc)((0,m.ll)({name:"www/watch",deps:["www/common"],page:"watch",init:function(){oL();var a,b;(0,m.C)(window.document.body,"watch8")?(a=(0,m.H)("watch8-action-buttons"),b=(0,m.H)("watch8-action-panels")):(a=(0,m.H)("watch7-action-buttons"),b=(0,m.H)("watch7-action-panels"));DN=null;a&&b&&(DN=new wM(a,b));CN=new QM;pK();(0,m.L)(window.document,"keypress",zK);(0,m.w)("SKIP_RELATED_ADS")||((0,m.Hc)()?GN=(0,m.Jc)(hJ,void 0):hJ());AK();a=(0,m.H)("watch7-sidebar");FN.push((0,m.R)(a,"click",oN,"related-action"));
FN.push((0,m.R)(a,"click",pN,"resumable-list"));(a=(0,m.KG)())&&a.getPlayerState&&1==a.getPlayerState()?(0,m.BD)():EN.push((0,m.z)("player-state-change",RM));SM();m.Td&&(!window.document.documentMode||8>window.document.documentMode)&&HN.push((0,m.R)(window.document.body,"click",qN,"video-thumb"));a=(0,m.w)("RELATED_DELAY_LENGTH");b=!!(0,m.I)("guide-module-loading");var c=3E3==a;if(b){var d=["guide"];c&&d.push("related");rN(d)}!a||b&&c||vN(a);a=["comments"];(0,m.w)("DELAY_LOAD_FOOTER")&&a.push("footer");
wN(a);(0,m.yE)();(0,m.w)("FACEBOOK_TOKEN_REFRESH_ENABLED")&&(a=(0,m.H)("facebook_token_refresh_iframe"),b=(0,m.w)("FACEBOOK_TOKEN_REFRESH_URL"),a&&(0,m.xf)("facebook_token_refresh")!=b&&((0,m.uf)("facebook_token_refresh",b,3600),a.src=b))},dispose:function(){DN&&((0,m.Wa)(DN),DN=null);CN&&((0,m.Wa)(CN),CN=null);(0,m.Tk)(window.document,"keypress",rK);(0,m.Tk)(window.document,"click",sK);qK=-2;(0,m.Tk)(window.document,"keypress",zK);null!=window.adModuleLoaded&&(0,m.Xl)("adModuleLoaded");(0,m.y)(KJ);
lJ&&(lJ=null);iJ&&(iJ.dispose(),iJ=null);kJ=rJ=qJ=pJ=null;xJ=JJ=!1;if(yJ){for(var a=yJ.length-1;0<=a;a--)(0,m.Xl)(yJ[a]);yJ=[]}(0,m.BE)();hL(0);(0,m.M)(LK);LK.length=0;a=IK;IK=null;a&&(a.removeEventListener("onCueRangeEnter",dL),a.removeEventListener("onReady",JK),a.isReady()&&a.removeCueRange("AUTOPLAY_PREFETCH"));(0,m.nb)(RK);RK.length=0;BK&&(0,m.F)(BK,"scrolled");bL=fL=!1;GK=FK=EK=DK=OI=CK=BK=null;HK="";gL&&((0,m.y)(gL),gL=null);(0,m.Kc)(eL);(a=(0,m.H)("guide-container"))&&(0,m.F)(a,"branded");
if(a=(0,m.H)("player"))a.style.background="";FN&&((0,m.M)(FN),FN=[]);(0,m.nb)(EN);EN.length=0;(0,m.nb)(aN);aN.length=0;(0,m.M)(UM);UM.length=0;TM&&(dN(),kN=iN=jN=TM=null,(0,m.cD)());(0,m.M)(HN);HN.length=0;(0,m.nb)(IN);IN.length=0;(0,m.Kc)(GN);for(var b in sN)(0,m.y)(sN[b]);sN={};(0,m.M)(tN.ov);zN?(0,m.CG)():(fK&&(fK.destroy(),fK=null),AN&&(AN.destroy(),AN=null),(0,m.M)(BN),BN.length=0);KL()}}));})(_yt_www);
